### DISCUSSION TITLE
PHP8 Support

### DISCUSSION THREAD

**Discussion by antonmedv** [deployphp/deployer#2351] [General]
Current stable version v6.8.0 does not support PHP8 due to next facts:
- composer.json restriction on ~7.0
- requirement of Symfony components also lacks PHP8 support
- deployphp/recipes also require ~7.0
- possible unknown backward incompatibility with php8. 

Solutions to this problem:
### Upgrade to Deployer v7.
  - Currently in beta 
  - Upgrade docs are here: 
     https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md#upgrade-from-6x-to-7x
  - Best possible solution, but requires some time.
### Switch to `deployer/dist` 
   - https://github.com/deployphp/distribution
   - This is phar version of dep tool. Everything will work same. 

### Solution for deployphp/recipes
  - Just copy paste needed recipes.

**Comment by ROTGP** [comment]
I have been using v6.8 with PHP7.4 and I've been very happy with it, but now that I'm required to use PHP 8 I'm afraid that I'll have to look for another solution. 

As for the beta version being the "Best possible solution" - I've already lost a couple of days trying to make this work, and with no success. The "[upgrade guide](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md#upgrade-from-6x-to-7x)" is vague and confusing ("Change hostname to alias", and then "alias() is deleted, host() itself sets alias" - what?). Things that were working well before are breaking (the 'cleanup' task, rsync in general, recipe integration, etc). 

It would be _extremely_ helpful to provide some examples of common usage for v7, especially for using the rsync recipe.  

Thanks for your work and I hope that you manage to get v7 sorted out - I really love deployer.

**Reply by antonmedv** [reply]
> host() itself sets alias" - what?

It works the same in v6. I just renamed it. 

I have a few things before I be able to release v7. Also working on better docs.

**Reply by ROTGP** [reply]
Wouldn't it make more sense to first make a release that supports PHP 8, and then another release to refactor the api? It seems like doing both at the same time is a bit ambitious.

**Reply by antonmedv** [reply]
At first, it looks more sense.

**Reply by staabm** [reply]
@ROTGP the phar dist version does not work for you?

**Reply by ROTGP** [reply]
@staabm I ended up opting for a simpler deployment strategy with fewer dependencies - this package has been great but in the end PHP8 has been out for 4 months and having to mess around with trying to integrate the (unstable) beta version into my github-action workflow was a nightmare.  Now I'm using this [SSH](https://github.com/appleboy/ssh-action) action combined with shell scripting which I find faster, with fewer dependencies, and more flexible.

**Reply by antonmedv** [reply]
If you like yaml more:
```
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
```

Than PHP:

```php
task('build', function () {
    run('whoami');
});
``` 

😄
