### DISCUSSION TITLE
a few questions (hide yaml/non-yaml tasks, default stages/hosts)

### DISCUSSION THREAD

**Discussion by freywald** [deployphp/deployer#2434] [Help needed]
Hello,

I've got a few questions.

## 1. hide tasks after they've been defined

In my recipe I reuse official tasks

require 'recipe/deploy/cleanup.php';

but I'd like some tasks (all deploy:*) to be hidden from the menu when running plain $ dep.

Can I hide the task after it was defined? I want to hide all the deploy:xxx tasks and call them via invoke/before/grouping in my recipe myself.

## 2. hide yaml tasks if the last name of namespace contains a dot at the identifier start

Can a yaml task be hidden from the menu if it begins with a dot?

example
```yaml
tasks:
    local:.initialize:
        script:
            - cd {{base_directory}}
            #- bla bla composer test ....
```
initialize should not show up in menu ($ dep).

## 3. default stages/hosts

Is there a default_stage or default_host variable? When defining a local task I am still asked for a host ("Select hosts: (comma separated)" [...]).
Also having a default host or stage for non-local tasks is nice. There was in v6, but how is it done in v7?
