### DISCUSSION TITLE
Github action fails with Command "deploy" is not defined.

### DISCUSSION THREAD

**Discussion by dingo-d** [deployphp/deployer#2493] [Help needed]
Hi!

I'm trying to run deployer from GH actions to deploy to my remote server, but I keep running into issues.

I'm not using the default action (I'm seriously considering it), but I created my own action

```yaml
name: Deploy to staging

on:
  # Run on pushes to `staging` branch
  push:
    paths-ignore:
      - '**.md'
    branches:
      - staging
  # Allow manually triggering the workflow.
  workflow_dispatch:

defaults:
  run:
    working-directory: ./wp-content/themes/wordpress-cicd

jobs:
  deploy-stage:
    name: Deploy to staging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        node: [12.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2, deployer, wp-cli

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Deploy application
        env:
          role_id: ${{ secrets.VAULT_AUTH_ROLE_ID }}
          secret_id: ${{ secrets.VAULT_AUTH_SECRET_ID }}
          vault_address: ${{ secrets.VAULT_AADDR }}
        run: |
          deployer -f.github/deploy.php deploy "$role_id" "$secret_id" "$vault_address" staging -vvv
```

My deployer config and setup is located in the `.github` folder (kinda made sense to me not to pollute the repo plus the deployment will be run on the GH action either way). The `-vvv` was added so that I can troubleshoot the deployment process.

When I run it either locally using `act` or by pushing to my staging branch I get the same error

```bash
| In Application.php line 645:
|
|   [Symfony\Component\Console\Exception\CommandNotFoundException]
|   Command "deploy" is not defined.
|
|
| Exception trace:
|   at phar:///usr/local/bin/deployer/vendor/symfony/console/Application.php:645
|  Symfony\Component\Console\Application->find() at phar:///usr/local/bin/deployer/vendor/symfony/console/Application.php:229
|  Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/deployer/vendor/symfony/console/Application.php:141
|  Symfony\Component\Console\Application->run() at phar:///usr/local/bin/deployer/src/Deployer.php:326
|  Deployer\Deployer::run() at phar:///usr/local/bin/deployer/bin/dep:136
|  require() at /usr/local/bin/deployer:4
```

Does anybody have any idea why that would happen? When I exec to the container that will run the action I can see that the `deployer` command exists, and I can even `cat` it (`cat /usr/local/bin/deployer`), but I keep getting the error.

The structure of my setup is

```
root
  .github
    deploy/
      tasks/
      other php files I'm requiring in the deploy.php file
    deploy.php
```

And my `deploy.php` looks like this:

```php
<?php

namespace Deployer;

require 'recipe/common.php';

require 'deploy/config.php';
require 'deploy/staging.php';
require 'deploy/production.php';
require 'deploy/development.php';
require 'deploy/tasks.php';
```

EDIT:

Tried deploying with the action but this also fails

```yaml
      - name: Deploy application
        env:
          role_id: ${{ secrets.VAULT_AUTH_ROLE_ID }}
          secret_id: ${{ secrets.VAULT_AUTH_SECRET_ID }}
          vault_address: ${{ secrets.VAULT_AADDR }}
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: -f.github/deploy.php deploy "$role_id" "$secret_id" "$vault_address" staging -vvv
```

> Command failed with ENOENT: deployer.phar -f.github/deploy.php deploy $role_id $secret_id $vault_address staging -vvv
spawnSync deployer.phar ENOENT

**Comment by dingo-d** [comment]
Not sure why, but having the `deploy.php` in a folder is not something that GH actions are comfortable with 🤷🏼‍♂️ 

I've moved the `deploy.php` to the root of the repo and now the deployment commands work (without the `-f` flag ofc).

**Reply by antonmedv** [reply]
This may be an indicator of a bug in shell arguments parsing in deployphp/action.

**Reply by dingo-d** [reply]
In the end I didn't use the action, my workflow for GH deploy to staging action looks like this:

```yaml
name: Deploy to staging

on:
  # Run on pushes to `staging` branch
  push:
    paths-ignore:
      - '**.md'
    branches:
      - staging
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  deploy-stage:
    name: Deploy to staging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        node: [12.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2, deployer, wp-cli

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
            ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy application
        env:
          role_id: ${{ secrets.VAULT_AUTH_ROLE_ID }}
          secret_id: ${{ secrets.VAULT_AUTH_SECRET_ID }}
          vault_address: ${{ secrets.VAULT_ADDR }}
          admin_user: ${{ secrets.ADMIN_USER }}
          admin_email: ${{ secrets.ADMIN_EMAIL }}
          admin_password: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          deployer deploy "$role_id" "$secret_id" "$vault_address" "admin_user" "admin_email" "admin_password" staging
```

I'm passing extra input arguments to the deploy action so that I can build everything on the server correctly.

With the `deploy.php` in the repo root, this seems to work perfectly.
