### DISCUSSION TITLE
YAML - Custom script not firing.

### DISCUSSION THREAD

**Discussion by iBotPeaches** [deployphp/deployer#2508] [Help needed] [answered]
So I converted a project over to deployer7 and for some reason my custom task appears to run, but actually not. I have a deploy task that looks like:

```
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - yarn:install
    - yarn:run:prod
    - deploy:publish
  yarn:run:prod:
    script:
      - 'cd {{release_or_current_path}} && yarn run prod'
```

dep deploy has no errors, but the site is broken because no production assets generated. I look at the debug output and get nothing:

```
done yarn:install 26s 122ms
task yarn:run:prod
done on prod
    
done yarn:run:prod 152ms
```

I must be doing something dumb but can't pinpoint it - any ideas?
