### DISCUSSION TITLE
Using environment variables from gitlab

### DISCUSSION THREAD

**Discussion by ghost** [deployphp/deployer#2547] [Help needed]
Hi,
 Its not good practice to keep production .env details in git. As there will be keys and passwords.
 
 I was hoping to define those in environment variables of gitlab, and use them in yaml file.
 
 But i am not sure how would i achieve that. I searched here in issues also didnt find anything in documents.
 
```
import:
    - recipe/laravel.php
    - contrib/php-fpm.php
    - contrib/npm.php

config:
  application: 'portal'
  repository: 'git@gitlab.com:devxworld.io/[repositoryHere.git]'
  base_deploy_path: '/var/www'
  php_fpm_version: '8.0'
  ssh_multiplexing: false

hosts:
  prod:
    remote_user: root
    hostname: 'xxx.xxx.xxx.xxx'
    deploy_path: '{{base_deploy_path}}/portal.haider.pw'
    identify_file: '~/.ssh/mysshFile'
    branch: 'countinous_deployment'

tasks:
  create:env:
    - 'cd {{release_path}} && sudo cp -R .env.example .env'
    - 'cd {{release_path}} && {{bin/php}} artisan key:generate'
  deploy:
    - deploy:prepare
    - deploy:vendors
    - create:env
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_path}} && npm run prod'

after:
  deploy:failed: deploy:unlock

```

Here i tried to copy the .env.example to .env, but still its not what i am looking for. 
I was hoping to have environment variables fetched from gitlab or github that is being manually defined there by me.

**Comment by benjaminmal** [comment]
I don't know if it answers your question but you can do this to define manually a environment variable:

```yaml
config:
  env:
    API_PASSWORD: 'your_api_password'
```
