### DISCUSSION TITLE
->local() in YAML configuration

### DISCUSSION THREAD

**Discussion by ulrichmathes** [deployphp/deployer#2552] [Help needed]
Hey, i want to define a small task within `deploy.yaml` with deployer v7

```yml
tasks:
  test:
    local: true
    script: 'cd {{release_path}}ext/sitepackage/ && yarn install --silent && yarn build'
```

But sadly that does not work. Is there an other configuration that i haven't seen?

The old php variant:
```php
task('test', function () {
  run('cd {{release_path}}ext/sitepackage/ && yarn install --silent && yarn build');
})->local();
