### DISCUSSION TITLE
latest beta with new yml: host not found / use set in yml

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2585] [Help needed]
I am using this latest yaml file with Deployer 7 beta installed using ` composer require deployer/deployer:dev-master`:

```yml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'domain'
  repository: 'git@github.com:me/domain.git'
  php_fpm_version: '7.4'

hosts:
  prod:
    remote_user: forge
    hostname: 'domain.com'
    deploy_path: '~/{{hostname}}'
  staging:
    remote_user: forge
    hostname: 'staging.domain.com'
    deploy_path: '~/{{hostname}}'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_or_current_path}} && npm run prod'

after:
  deploy:failed: deploy:unlock
```

On doing a shell test I get 

```bash
dep ssh staging.domain.com
In HostCollection.php line 19:
  Host `staging.domain.com` not found                                     
ssh [<hostname>]
```

Doing a simple ssh I do get in so domain can be located:

```ssh
ssh forge@staging.domain.com
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-143-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Jun 23 01:10:43 UTC 2021
...
```

when I try host instead of hostname I get the same error. What am I missing here?

Two, how do I use this PHP in the yaml file instead:

```php
set('keep_releases', 10);

// Make sure uploads & published , tls, logs aren't overwritten by deploying
set('shared_dirs', [
    'public/uploads',
    'public/published',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
    'storage/app/modules',
]);
set('shared_files', [
    '.env',
    '.keyname_private_key',
]);
set('writable_dirs', [
    'public/uploads',
    'public/published',
    'storage/framework/cache/data',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
    'storage/app/modules',
]);
```

Also, initial `dep init` generated `deploy.php` but not a `deploy.yml`. Thought it would?

**Comment by jasperf** [comment]
I think set is just part of config so adjusted `deploy.yml` :

```yml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'domain'
  repository: 'git@github.com:me/domain-v3.git'
  php_fpm_version: '7.4'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.name_private_key'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads',
    - 'public/published',
    - 'storage/framework/cache/data',
    - 'storage/logs',
    - 'storage/tls',
    - 'storage/app/public',
    - 'storage/app/modules',

hosts:
  prod:
    remote_user: forge
    hostname: 'domain.com'
    deploy_path: '~/{{hostname}}'
  staging:
    remote_user: forge
    hostname: 'staging.domain.com'
    deploy_path: '~/{{hostname}}'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_or_current_path}} && npm run prod'

after:
  deploy:failed: deploy:unlock
  queue: restart
  artisan: horizon:terminate

```

still cannot run `dep ssh staging` though. Also not sure if all is correct yet.

**Comment by jasperf** [comment]
Hmmm, `dep` still runs old global deployer 6.8 and not sure how to update it with curl. So I had to use ` php vendor/bin/dep init` to use the latest version and get the latest script to run.

**Comment by jasperf** [comment]
This version does work with `php vendor/bin/dep`:

```yml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'domain'
  repository: 'git@github.com:jasperf/domain-v3.git'
  php_fpm_version: '7.4'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    remote_user: forge
    hostname: 'domain.com'
    deploy_path: '~/{{hostname}}'
  staging:
    remote_user: forge
    hostname: 'staging.domain.com'
    deploy_path: '~/{{hostname}}'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_or_current_path}} && npm run prod'

after:
  deploy:
    - failed:deploy:unlock
    - artisan:horizon:terminate
```
