### DISCUSSION TITLE
Segmentation faults after installing pcntl module.

### DISCUSSION THREAD

**Discussion by dabonzo** [deployphp/deployer#2591] [General]
I'm using php8 on OpenSuSe Tumbleweed, server is the latest Debian, and I need the pcntl module activated. However, after installing pcntl I get only Segmentation faults
```
10:56 $ dep -vvv deploy
[prod] ssh -O check '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/home/ad/.ssh/deployer_root@dsfafs' echo 2>&1
[prod] Master running (pid=20960)
[prod] /usr/bin/php /home/sadfa/vendor/deployer/deployer/bin/dep worker --task deploy:info --host prod --port 35299 --decorated -vvv                                                     
[prod] info deploying develop
done on prod
task deploy:setup
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Aborted (core dumped)
```
or
```
10:56 $ dep -vvv deploy
[prod] ssh -O check '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/home/dsfs/.ssh/deployer_root@sdfsdf' echo 2>&1
[prod] Master running (pid=20960)
[prod] /usr/bin/php /home/sfdsdfs/vendor/deployer/deployer/bin/dep worker --task deploy:info --host prod --port 41263 --decorated -vvv                                                     
[prod] info deploying develop
done on prod
task deploy:setup
Illegal instruction (core dumped)
```
deploy.yaml
```
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php
config:
  application: 'dfgdfgf'
  repository: 'git@dfgdfgdfg.git'
  branch: 'develop'
  php_fpm_version: '8.0'
  http_user: fgdgffdg
  http_group: clidgffgdfe
  writable_mode: chown

hosts:
  prod:
    hostname: 'dfgdfg'
    remote_user: root
    deploy_path: '/var/www/dfgdfgdfg'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - npm:install
    - npm:run:prod
    - deploy:writable
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_path}} && npm run prod'

after:
  deploy:failed: deploy:unlock
```

Any ideas how to solve this ?
