### DISCUSSION TITLE
Error: Command failed with exit code 1: vendor/bin/dep deploy -vvv

### DISCUSSION THREAD

**Discussion by zahhar** [deployphp/deployer#2653] [Help needed] [answered]
Hi all,

I feel like I tried everything to get Deployer v7 run as a Github Action triggered manually, but it fails with error:
`Error: Command failed with exit code 1: vendor/bin/dep deploy -vvv`

Locally it works fine.

My action code:

```
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2, deployer:v7

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy -vvv
```

What I tried:
- Verbosity does not help: nothing gets printed to output. Seems it dies before it can print anything.  
- Downgrading PHP to v7.4 does not help either - same result. 
- Removing `deployer:v7` from "Setup PHP" action leads to downloading `deployer.phar` that will be v6.8 and won't fit my deploy.php file. 
- My `deploy.php` is on root level and it has only one host and one task — so nothing to configure. 
- Secrets are configured fine - double checked.

What I am missing?

**Comment by antonmedv** [comment]
I’ll try to take a look.

**Comment by zahhar** [comment]
@antonmedv - I spent some time analyzing the issue and came to the working solution both for Deployer 6.8 and Deployer 7.0 (beta).

**My summary:**  This is because of randomly appearing`crc32` errors that make the whole process unreliable. For me `crc32` error appears in more of 50% cases when I run Deployer 7 no matter where - locally on my MacOS Big Sur, or in Github Action running latest Ubuntu agent. So I had to revert to Deployer 6.8 and PHP 7.4 that work fine everywhere. 

**Note on ssh-multiplexing:** I observed the issue with ssh connection happens in Github Action running ubuntu-latest agent pretty often. So I would propose to set switch it off in default Deployer configuration. It works much more stable then. 

**Here is my working Github Action workflow that works both for Deployer 7.0 and Deployer 6.8**. 
You only need to provide `deployer_url` and you are fine to go. 

```
env:
  host_name: hostname-without-https.example.com
  key_filename: private.key
  deployer_url: https://deployer.org/releases/v7.0.0-beta.24/deployer.phar

jobs:
  deploy:
    name: Deployer Test
    runs-on: ubuntu-latest
    
    environment:
        name: dev
        url: "https://${{ env.host_name }}"

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Check dependencies for known vulnerabilities
        uses: symfonycorp/security-checker-action@v2
        
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ env.host_name }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.PRIVATE_KEY }}" > /home/runner/.ssh/${{ env.key_filename }}
          chmod 600 /home/runner/.ssh/${{ env.key_filename }}
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/${{ env.key_filename }}
      
      - name: Download Deployer
        run: |
          wget -O deployer.phar ${{ env.deployer_url }}
          chmod +x deployer.phar
  
      - name: Deploy to host
        run: |
          php deployer.phar deploy
```
And here is my `deploy.php` that also works for both version after you comment/uncomment respective blocks. Now it is configured to deploy **Lumen app** using **Deployer 7**. 

```
<?php
namespace Deployer;

require 'recipe/laravel.php';

set('bin/php', function () {
    return '/opt/php74/bin/php';
});

set('bin/composer', function () {
    return '/opt/php74/bin/php /usr/local/bin/composer';
});

// Project name
set('application', 'appname');

// Project repository
set('repository', 'git@github.com:org/repo.git');

// Other config
set('allow_anonymous_stats', false);
set('keep_releases', 1);

// Shared files/dirs between deploys 
set('shared_files', [
    '.env'
]);
add('shared_dirs', []);

set('writable_dirs', [
    'storage'
]);

// Deployer 6.x only
//set('default_stage', 'dev');

//host('example.com')
//    ->stage('dev')
//    ->user('admin')
//    ->identityFile('~/.ssh/private.key')
//    ->set('deploy_path', '/var/www')
//    ->set('dotenv', '{{deploy_path}}/shared/.env')
//    ->multiplexing(false);

// Deployer 7.x only
host('example.com')
    ->set('labels', ['stage' => 'dev'])
    ->set('remote_user','admin')
    ->set('deploy_path', '/var/www')
    ->set('dotenv', '{{deploy_path}}/shared/.env')
    ->set('multiplexing',false)
    ->set('identity_file','~/.ssh/private.key');

//Now define your tasks after this line
```
