### DISCUSSION TITLE
Deployer 7 Host staging not found

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2705] [Help needed] [answered]
I ran `dep ssh staging` and got 

```sh
In HostCollection.php line 20:
                             
  Host "staging" not found.  
```

I am using this for the hosts path in my `deploy.yml` file:

```yaml
hosts:
  prod:
    remote_user: forge
    hostname: 'domain.com'
    deploy_path: '~/{{hostname}}'
  staging:
    remote_user: forge
    hostname: 'staging.domain.com'
    deploy_path: '~/{{hostname}}'
```

And I am using latest Deployer:

```
dep --version
Deployer 7.0.0-master
```

and when I check config it only loads localhost for some reason ..

```
ep config
{
    "@localhost": {
        "alias": "@localhost",
        "hostname": "@localhost"
    }
}
```

and dep is loaded from global package, not project package:

```
 jasper@MacMini  ~/code/domain.com/domain.com   php8  which dep
/Users/jasper/.composer/vendor/bin/dep
```

I also tried full domain `staging.domain.com`. No dice. Do I need to add another option here?
