### DISCUSSION TITLE
Deployer 7 Use - deploy:publish & composer install

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2707] [Help needed]
### Deploy Publish

What does `- deploy:publish` do in a `deploy.yaml` file? I do not mind adding this to documentation later as well, but could not find it yet. Was considering using

```yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:queue:restart
    - queue:restart
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_or_current_path}} && npm run prod'
```

but may remove:

```yaml
    - npm:install
    - npm:run:prod
```

as I build packages locally and not need `node_modules` on the server per se.

### Composer Install
Other thing I wondered about is how `composer install` is run. In the old `deploy.php` we have this did run

```php
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'vendor/deployer/recipes/recipe/cachetool.php';

// Configuration
set('repository', 'git@github.com:domain/domain-app.git');
set('default_stage', 'production');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
set('ssh_type', 'native');
set('cachetool', '/var/run/php/php7.4-fpm.sock');
set('keep_releases', 10);

// Make sure uploads & published , tls, logs aren't overwritten by deploying
set('shared_dirs', [
    'public/uploads',
    'public/published',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
    'storage/app/modules',
]);
set('shared_files', [
    '.env',
    '.transip_private_key',
    'storage/app/exact.api.json',
]);
set('writable_dirs', [
    'public/uploads',
    'public/published',
    'storage/framework/cache/data',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
    'storage/app/modules',
]);

// SMART CUSTOM DEPLOY COMMANDS
task('db:migrate', function () {
    run('cd {{release_path}} && php artisan migrate --force');
});
task('horizon:terminate', function () {
    run('cd {{release_path}} && php artisan horizon:terminate');
});

task('queue:restart', function() {
    run('cd {{release_path}} && php artisan queue:restart');
});

task('reload:php-fpm', function () {
run('sudo /etc/init.d/php7.4-fpm restart'); // Using SysV Init scripts
});


// Hosts
// dep deploy production
// dep deploy staging

   host('staging')
   ->hostname('staging.domain.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('staging')
//    ->set('branch', 'developer')
   ->set('deploy_path', '/home/forge/staging.domain.com');

   host('production')
   ->hostname('domain.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('production')
   ->set('deploy_path', '/home/forge/domain.com');

   host('prodold')
   ->hostname('prod-w-1.domain.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('prodold')
   ->set('deploy_path', '/home/forge/domain.com');

// Run database migrations
after('deploy:symlink', 'db:migrate');

// Restart job
after('db:migrate', 'queue:restart');

// Clear OPCache
after('queue:restart', 'cachetool:clear:opcache');
after('cachetool:clear:opcache', 'horizon:terminate');

after('deploy', 'reload:php-fpm');
after('rollback', 'reload:php-fpm');
```

 but not sure how it is triggered in the `yaml` file. Could not find it in `recipe/laravel.php`

**Comment by antonmedv** [comment]
You can examine task by:
dep tree deploy
And
dep deploy —plan

**Comment by jasperf** [comment]
@antonmedv I assume `dep deploy staging —plan` would be a dry run? 
Did try `dep tree deploy` already and was told 
```
Task `queue:restart` not found.
```

**Reply by antonmedv** [reply]
It’s not a dry run, it’s a plan)) Flattened list of tasks to run.

**Reply by jasperf** [reply]
I see. Well, will see if I can fix the horizon queue restart command first and then run the plan properly to see all tasks that will be run.

**Reply by jasperf** [reply]
The 

```yaml
- queue:restart
 ```

was duplicate of :
```yaml
- artisan:queue:restart
 ```

The task 
```yaml
after:
  deploy:
    - failed:deploy:unlock
``` 

does not work either though..

Full `.yaml`

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'our-app'
  repository: 'git@github.com:domain/our-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
    - 'storage/app/exact.api.json'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache'
    - 'storage/framework/sessions'
    - 'storage/framework/views'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    remote_user: forge
    hostname: 'domain.com'
    deploy_path: '~/{{hostname}}'
  staging:
    remote_user: forge
    hostname: 'staging.domain.com'
    deploy_path: '~/{{hostname}}'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:queue:restart
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  # npm:run:prod:
  #  script:
  #   - 'cd {{release_or_current_path}} && npm run prod'

after:
  deploy:
    - failed:deploy:unlock
```

**Reply by jasperf** [reply]
Seems `deploy: unlock` is part of `deploy:publish` https://github.com/deployphp/deployer/blob/master/recipe/common.php#L178-L184

**Reply by jasperf** [reply]
My tree is now

```sh
 dep tree deploy
The task-tree for deploy:
└── deploy
    ├── deploy:prepare
    │   ├── deploy:info
    │   ├── deploy:setup
    │   ├── deploy:lock
    │   ├── deploy:release
    │   ├── deploy:update_code
    │   ├── deploy:check_env  // before deploy:shared
    │   ├── deploy:shared
    │   └── deploy:writable
    ├── deploy:vendors
    ├── deploy:regenerate_key  // after deploy:vendors
    ├── artisan:storage:link
    ├── artisan:view:cache
    ├── artisan:config:cache
    ├── artisan:queue:restart
    ├── deploy:publish
    │   ├── deploy:symlink
    │   ├── deploy:unlock
    │   ├── deploy:cleanup
    │   └── deploy:success
    └── php-fpm:reload
```

I assume `deploy:vendors` is the php composer part? Check env and regenerate keys might be new compared to Deployer 6..

**Reply by antonmedv** [reply]
A few observations:

# To unlock deploy on failure:
```yaml
after:
  deploy:failed: deploy:unlock
```

# Avoid reloading php-fpm

~php-fpm:reload~

Will write a doc on this one.

# Config

Repeated stuff can be in config:

```yaml
config:
    remote_user: forge
    deploy_path: '~/{{hostname}}'

hosts:
  prod:
    hostname: 'domain.com'
  staging:
    hostname: 'staging.domain.com'
```

**Reply by jasperf** [reply]
@antonmedv thanks a lot for this feedback. Appreciate it. Updated it now to 

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'domain-app'
  remote_user: forge
  deploy_path: '~/{{hostname}}'
  repository: 'git@github.com:domain/domain-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
    - 'storage/app/exact.api.json'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache'
    - 'storage/framework/sessions'
    - 'storage/framework/views'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    hostname: 'domain.com'
  staging:
    hostname: 'staging.domain.com'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:queue:restart
    - deploy:publish

after:
  deploy:failed: deploy:unlock
```

Would also good to mention in documentation that `deploy.yaml` is picked up but `deploy.yml` is ignored.

**Reply by antonmedv** [reply]
> picked up but deploy.yml is ignored.

I fixed it and how it should be picked too.

**Reply by jasperf** [reply]
Updated to the latest. Good to have `deploy.yml` works as well . I realized I missed these two tasks still

```php
// SMART CUSTOM DEPLOY COMMANDS
task('db:migrate', function () {
    run('cd {{release_path}} && php artisan migrate --force');
});
task('horizon:terminate', function () {
    run('cd {{release_path}} && php artisan horizon:terminate');
});
```

Added these as new tasks. Wonder if I need to move to release path still to run these commands. The general deployment commands like a `deploy:regenerate_key` in `deploy:prepare` do not show this in the `dep tree deploy`:

```yaml
The task-tree for deploy:
└── deploy
    ├── deploy:prepare
    │   ├── deploy:info
    │   ├── deploy:setup
    │   ├── deploy:lock
    │   ├── deploy:release
    │   ├── deploy:update_code
    │   ├── deploy:check_env  // before deploy:shared
    │   ├── deploy:shared
    │   └── deploy:writable
    ├── deploy:vendors
    ├── deploy:regenerate_key  // after deploy:vendors
    ├── artisan:storage:link
    ├── artisan:view:cache
    ├── artisan:config:cache
    ├── artisan:queue:restart
    ├── artisan:horizon:terminate
    ├── artisan:migrate
    └── deploy:publish
        ├── deploy:symlink
        ├── deploy:unlock
        ├── deploy:cleanup
        └── deploy:success
```

and new tasks for migration and horizon terminate added I did use before printing the tree and there were no issues detected as you saw above.

```yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:queue:restart
    - artisan:horizon:terminate
    - artisan:migrate
    - deploy:publish
```

**Reply by jasperf** [reply]
Updated tasks a bit more and now have this list including `artisan:optimize` and a change of order of migration and horizon termination and such

```yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:optimize
    - artisan:migrate
    - artisan:queue:restart    
    - artisan:horizon:terminate
    - deploy:publish
```

Compared it to old Deployer deployment and seems some things were slightly different:


Deployer 6 deployment showed:

```
dep deploy:unlock staging
✔ Executing task deploy:unlock
➜  valet git:(master) dep deploy staging       
✈︎ Deploying master on staging
✔ Executing task deploy:prepare

```

and 7 shows info hereafter. Then we see the same again for 6 and seven:

```
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
```

then Deployer 7 added an `.env check.

```
Cloning into '/home/forge/staging.domain.com/releases/486'...
....
Connection to staging.domain.com closed.
✔ Ok
✔ Executing task deploy:shared
```

vendors in our new Deployer 7 setup is a separate tasks and so added after writable and is followed by regeneration of keys

```
✔ Executing task deploy:vendors
✔ Executing task deploy:writable
✔ Executing task artisan:storage:link
✔ Executing task artisan:view:cache
✔ Executing task artisan:config:cache

```

I miss optimize in new dep tree in Deployer 7 . Added.


```
✔ Executing task artisan:optimize
```

```
✔ Executing task deploy:symlink
✔ Executing task db:migrate
✔ Executing task queue:restart
```

no need for this cache tool anymore as we do not use opcache anymore

```
✔ Executing task cachetool:clear:opcache
```

```
✔ Executing task horizon:terminate
✔ Executing task deploy:unlock
✔ Executing task cleanup
Successfully deployed!
```
