### DISCUSSION TITLE
Importer doesn't ignore hidden keys

### DISCUSSION THREAD

**Discussion by kevinreniers** [deployphp/deployer#2709] [Help needed]
Hi, I'm trying to upgrade from v6.6.0 to the latest beta(34) of Deployer and trying to use a hosts.yaml file as my inventory. It seems that the Importer isn't ignoring hidden keys anymore.

```yaml
.base: &base
  remote_user: foo
  # etc

sv01:
  <<: *base
  remote_user: bar
```

Gives me this error:

```
 Deployer\Exception\Exception  in Importer.php on line 62:

  Wrong syntax in ".base:" section.

 Error  in Importer.php on line 60:

  Call to undefined method Deployer\Importer\Importer::.base()
```

In [v6.6.0](https://github.com/deployphp/deployer/blob/74b3f73e60acee2eccc0d53c270a7c4335d5b5a7/src/Host/FileLoader.php#L57-L59), the inventory function of the FileLoader class would skip these hidden keys.

Is there any way to work around this and could this be promoted to a bug report if it's an unintended change?

Thanks!

**Comment by kevinreniers** [comment]
I have a workaround by setting the hidden keys under the `config:` option. However, I think it should still work without this workaround. :smile: 

```yaml
config:
  .base: &base
    remote_user: foo
    # etc

hosts:
  sv01:
    <<: *base
    remote_user: bar
```
