### DISCUSSION TITLE
deployer 7 choose separate branch for staging

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2711] [Help needed] [answered]
What if I want to (temporarily) choose a different branch for deployment to staging? How would I add that to the `deploy.yml` file? I mean would this be the way:

```yaml
config:
  application: 'our-app'
  remote_user: forge
  deploy_path: '~/{{hostname}}'
  repository: 'git@github.com:domain/our-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
```
.....
```yaml
hosts:
  prod:
    hostname: 'domain.com'
  staging:
    hostname: 'staging.domain.com'
    branch: 'php8'
```

or is there a more appropriate way?

Did use it in new

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'domain-app'
  remote_user: forge
  deploy_path: '~/{{hostname}}'
  repository: 'git@github.com:domain/domain-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
    - 'storage/app/exact.api.json'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache'
    - 'storage/framework/sessions'
    - 'storage/framework/views'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    hostname: 'domain.com'
  staging:
    hostname: 'staging.domain.com'
    branch: 'php8'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:optimize
    - artisan:migrate
    - artisan:queue:restart    
    - artisan:horizon:terminate
    - deploy:publish

after:
  deploy:failed: deploy:unlock
```

and did see

```sh
ep deploy staging
[staging] info deploying php8                                                                                                                                                                          
task deploy:setup
task deploy:lock
task deploy:release
task deploy:update_code
task deploy:check_env
task deploy:shared
task deploy:writable
task deploy:vendors
task deploy:regenerate_key
task artisan:storage:link
task artisan:view:cache
task artisan:config:cache
task artisan:optimize
task artisan:migrate
task artisan:queue:restart
task artisan:horizon:terminate
task deploy:symlink
task deploy:unlock
task deploy:cleanup
[staging] info successfully deployed!
```

with indication of usage of `php8`. Did seem to be really slow somehow though hanging on vendors. Did update composer packages including latest Laravel.. but still.
