### DISCUSSION TITLE
Laravel (ReflectionException(code: -1): Class session does not exist

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2738] [Help needed] [answered]
Using Deployer 7 `dev-master` but perhaps not the very latest upadet and I am now getting:

```
[previous exception] [object] (ReflectionException(code: -1): Class session does not exist at /home/forge/staging.smart48sitecom/releases/4/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)
```

So I am thinking there may be an issue with caching settings..

Using this now

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'site-app'
  remote_user: forge
  deploy_path: '~/{{hostname}}'
  repository: 'git@github.com:site/site-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
    - 'storage/app/exact.api.json'
  shared_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache'
    - 'storage/framework/sessions'
    - 'storage/framework/views'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    hostname: 'site.com'
  staging:
    hostname: 'staging.site.com'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:optimize
    - artisan:migrate
    - artisan:queue:restart    
    - artisan:horizon:terminate
    - deploy:publish

after:
  deploy:failed: deploy:unlock

```

Any idea where I may have done something off in the deployment?
