### DISCUSSION TITLE
Could not read from remote repository. Please make sure you have the correct access rights

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#2758] [Help needed] [answered]
Never had this before

```
[staging]  error  in update_code.php on line 90:
[staging] run cd ~/staging.site.com/.dep/repo && (/usr/bin/git remote update 2>&1)
[staging] err mesg: ttyname failed: Inappropriate ioctl for device
[staging] Fetching origin
[staging] Host key verification failed.
[staging] fatal: Could not read from remote repository.
[staging] Please make sure you have the correct access rights
[staging] and the repository exists.
[staging] error: Could not fetch origin
[staging] exit code 1 (General error)
```

We normally grab latest code from Github and update server.

I tried `git_tty: true` inj `deploy.yml`and

```sh
Host staging.app.com
  UserKnownHostsFile /dev/null
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  ForwardAgent yes
```
in `~/.ssh/config` but still got 

```
[staging] err mesg: ttyname failed: Inappropriate ioctl for device
[staging] Fetching origin
[staging] Host key verification failed.
[staging] fatal: Could not read from remote repository.
[staging] Please make sure you have the correct access rights
[staging] and the repository exists.
[staging] error: Could not fetch origin
[staging] exit code 1 (General error)
task deploy:failed
task deploy:unlock
```

also all my releases were wiped!

```
ll
total 20
drwxrwxr-x  5 forge forge 4096 Nov 17 11:20 ./
drwxr-xr-x 12 forge forge 4096 Nov 17 11:04 ../
drwxrwxr-x  3 forge forge 4096 Nov 17 11:20 .dep/
lrwxrwxrwx  1 forge forge   10 Nov 16 07:11 current -> releases/9/
lrwxrwxrwx  1 forge forge   11 Nov 17 11:20 release -> releases/13/
drwxrwxr-x 12 forge forge 4096 Nov 17 11:20 releases/
drwxrwxr-x  5 forge forge 4096 Nov 17 11:04 shared/
```

and

```
release$ ll
total 8
drwxrwxr-x  2 forge forge 4096 Nov 17 11:20 ./
drwxrwxr-x 12 forge forge 4096 Nov 17 11:20 ../
```

@antonmedv What to do?

here full `deploy.yml`:

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'site-app'
  remote_user: forge
  deploy_path: '~/{{hostname}}'
  repository: 'git@github.com:site/site-app.git'
  php_fpm_version: '8.0'
  keep_releases: '10'
  shared_files: 
    - '.env'
    - '.transip_private_key'
    - 'storage/app/exact.api.json'
  shared_dirs:
    - 'bootstrap/cache'
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache'
    - 'storage/framework/sessions'
    - 'storage/framework/views'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'
  writable_dirs:
    - 'public/uploads'
    - 'public/published'
    - 'storage/framework/cache/data'
    - 'storage/logs'
    - 'storage/tls'
    - 'storage/app/public'
    - 'storage/app/modules'

hosts:
  prod:
    hostname: 'site.com'
  staging:
    hostname: 'staging.site.com'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:optimize
    - artisan:migrate
    - artisan:queue:restart    
    - artisan:horizon:terminate
    - deploy:publish

after:
  deploy:symlink: php-fpm:reload
  deploy:failed: deploy:unlock
```

Could have sworn we used _agent forwarding_ before. Not sure what the issue is now failing all and deleting all releases.

Did try

```yml
git_tty: true
 ssh_type: native
```

no dice either and still: `[staging] err mesg: ttyname failed: Inappropriate ioctl for device`

Read https://github.com/deployphp/deployer/discussions/2641 but no proper solution there yet.
