### DISCUSSION TITLE
Help with bug on githubaction

### DISCUSSION THREAD

**Discussion by guilhermebillig** [deployphp/deployer#2943] [Help needed]
Iam getting the following error only on github action

Deployer version 7.0.0-rc.4

```
Using "deployer.phar".

Error: ] Call to undefined function Deployer\import()                           

 #0                                                                             
 phar:///home/runner/work/[...]/deployer.phar/src/Deploy
 er.php(388): require()                                                         
 #1 [internal function]: Deployer\Deployer::Deployer\{closure}()                
 #2                                                                             
 phar:///home/runner/work/[...]/deployer.phar/src/Deploy
 er.php(396): call_user_func()                                                  
 #3                                                                             
 phar:///home/runner/work/[...]/deployer.phar/src/Deploy
 er.php(3[22](https://github.com/[...]/runs/5046225220?check_suite_focus=true#step:4:22)): Deployer\Deployer::loadRecipe()                                   
 #4                                                                             
 phar:///home/runner/work/[...]/deployer.phar/bin/dep(13
 6): Deployer\Deployer::run()                                                   
 #5 /home/runner/work/[...]/Golden-Reports/deployer.phar(4):
```

```
deploy.php
<?php

namespace Deployer;

use Illuminate\Support\Facades\Log;

require 'recipe/laravel.php';

try {
    import(__DIR__ . '/hosts.yml');
} catch (Exception\Exception $e) {
    Log::error($e->getMessage(), $e->getTrace());
}

// Project name
set('application', '[...]');

// Project repository
set('repository', '[...]');

// Composer options
set(
    'composer_options',
    '--verbose --no-progress --no-interaction --no-dev --optimize-autoloader --ignore-platform-reqs'
);

after('deploy:failed', 'deploy:unlock');

```

```
hosts.yml
hosts:
  development:
    branch: develop
    hostname: [...]
    http_user: [...]
    deploy_path: /home2/[...]/domains/[...]
    writable_mode: chmod
  homologation:
    branch: homologation
    hostname: [...]
    http_user: [...]
    deploy_path: /home2/[...]/domains/[...]
    writable_mode: chmod
  production:
    branch: master
    hostname: [...]
    http_user: [...]
    deploy_path: /home2/[...]/domains/[...]
    writable_mode: chmod
```

```
workflow.yml
name: Deploy on development

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' // I tried 8.0, 7.4, 7.3

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy development
          private-key: ${{ secrets.PRIVATE_KEY }}
          ssh-config: |
            Host [...]
              HostName [...]
              User [...]
              Port [...]
          known-hosts: |
            [...]
```
