### DISCUSSION TITLE
tty remains true

### DISCUSSION THREAD

**Discussion by pavelgross** [deployphp/deployer#2955] [Help needed]
Hello all,
I am setting up a shopware deployment with deployer v6.8 via gitlab CI. 

git_tty is not configured - default false. Even if I explicitly set it to false I get the same result.

The deployment goes through so far even git clone from 2 different repos with "['tty' => true]" works fine. Only at the end after the 
➤ Executing task deploy:unlock
- done on [stage2]
✔ Ok [27ms]

I get the error
```
In Process.php line 1063:
                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  TTY mode requires /dev/tty to be read/writable.         
                                                          
Exception trace:
  at /.composer/vendor/symfony/process/Process.php:1063
 Symfony\Component\Process\Process->setTty() at /.composer/vendor/deployer/deployer/src/Ssh/Client.php:74
 Deployer\Ssh\Client->run() at /.composer/vendor/deployer/deployer/src/functions.php:304
 Deployer\run() at /builds/online/[MASKED]/deployer/deploy.php:53
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at /.composer/vendor/deployer/deployer/src/Task/Task.php:105
 Deployer\Task\Task->run() at /.composer/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at /.composer/vendor/deployer/deployer/src/Console/TaskCommand.php:144
 Deployer\Console\TaskCommand->execute() at /.composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /.composer/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at /.composer/vendor/deployer/deployer/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at /.composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /.composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /.composer/vendor/deployer/deployer/src/Deployer.php:326
 Deployer\Deployer::run() at /.composer/vendor/deployer/deployer/bin/dep:136
 include() at /.composer/vendor/bin/dep:102
```

What can be the cause for this? Can the tty still be configured somewhere? Can it be avoided with deployer v7.x?

Thanks a lot in advance.

**Comment by antonmedv** [comment]
In v7 git_tty was remove completely. Instead populate known_hosts beforehand.

**Reply by pavelgross** [reply]
Ok, then it seems I need to convert this to v7. My problem with v7 right now is that I do a lot of configuration via inventory (with roles, stages, etc.), and in v7 it's different with `import` and there's no documentation for it yet.

**Reply by antonmedv** [reply]
Will write better docs for sure. Can you share your configuration?

**Reply by pavelgross** [reply]
@antonmedv I understand that, not all at once. Anyway, thanks for your work and great tool.
My inventory.yml in v6 looks like this 
```
stage1:
  hostname: stage-host
  forwardAgent: true
  multiplexing: true
  ssh_type: native
  user: www-data
  roles:
    - app
    - script
  keep_releases: 3
  stage: stage

prod1:
  hostname: prod-host
  forwardAgent: true
  multiplexing: true
  ssh_type: native
  user: www-data
  keep_releases: 3
  roles:
    - app
  stage: production

....
prod2
....
stage2
...

```

**Reply by pavelgross** [reply]
For example, what I don't understand in v7 is - in the inverntory/import file (and also in deploy.php) I have predefined deploy tasks. 
```
tasks:
  deploy:
    - deploy:info
    - deploy:prepare
    - deploy:lock
    - deploy:release
    - deploy:update_code
    - deploy:shared
    - sw:deploy
    .....
```
But after `dep deploy` I see the steps, and it ends with an exception. 
```
  www-data@123:/var/www/html# dep deploy
  task deploy:info
  [stage] info deploying master
  task deploy:info
  [vm02-stg] info deploying master
  task deploy:setup
  task deploy:lock
  [stage]  Deployer\Exception\GracefulShutdownException  in lock.php on line 13:
  [stage]
  [stage]   Deploy locked.
  [stage]   Execute "deploy:unlock" task to unlock.
  [stage]
```
where do these deployment steps come from?

**Reply by pavelgross** [reply]
ok, get it. It's the deploy:prepare task defined in common.php

**Reply by antonmedv** [reply]
Yes, you can find it two ways:
```
dep tree deploy
```
And 
```
dep deploy --plan
```

**Reply by pavelgross** [reply]
nice 👍 thx

**Reply by pavelgross** [reply]
Last question: How do I do the configuration for different hosts in the inventory/import file? I need to define at least `deploy_path` for each host. In v6 you could do this quite well via `stage`.  It looks like `config` is not designed for this.
```
config:
  application: stage2
  alias: vm-app1
  deploy_path: '/var/www/app1'
  forwardAgent: true
  multiplexing: true
  ssh_type: native
  stage: stage
  remote_user: www-data
  keep_releases: 3

hosts:
  vm-app1:
    local: false
  vm-app2:
    local: false
    ....

```
