### DISCUSSION TITLE
update_code error in Deployer v7

### DISCUSSION THREAD

**Discussion by craigrileyuk** [deployphp/deployer#3011] [Help needed]
Having an issue getting a v7 of deployer up and running. Using Laravel 9 with PHP 8 via Github Actions

### composer.json
```json
"require-dev": {
		"deployer/dist": "^7.0.0-rc.4",
}
```

### Github Action log
```log
   =============================================================================
  /usr/local/cpanel/3rdparty/lib/path-bin/git clone --mirror  /home/siteroot/.dep/repo 2>&1
  [xx.xxx.xx.xxx] /etc/profile: line 94: GNU: command not found
  [xx.xxx.xx.xxx] TERM environment variable not set.
  [xx.xxx.xx.xxx] Host VPS
  [xx.xxx.xx.xxx] ============================================================================
  [xx.xxx.xx.xxx] Company Ltd
  [xx.xxx.xx.xxx] server03.host.co.uk
  [xx.xxx.xx.xxx] ============================================================================
  [xx.xxx.xx.xxx] UPTIME..: 01:59:40 up 49 days, 19:12,  1 user,  load average: 1.06, 1.10, 1.15
  [xx.xxx.xx.xxx] KERNEL..: 3.10.0-1160.53.1.el7.x86_64
  [xx.xxx.xx.xxx] DIST....: CentOS Linux release 7.9.2009 (Core)
  [xx.xxx.xx.xxx] Recent Logins:
  [xx.xxx.xx.xxx] myuser pts/0        xxx.xxx.xxx.xx   Sat Mar 12 01:09   still logged in   
  [xx.xxx.xx.xxx] myuser pts/0        xxx.xxx.xxx.xx   Sat Mar 12 00:52 - 00:58  (00:05)
  [xx.xxx.xx.xxx] Current Users:
  [xx.xxx.xx.xxx] myuser  pts/0  2022-03-12  01:09  (xxx.xxx.xxx.xx)
  [xx.xxx.xx.xxx] =============================================================================
  [xx.xxx.xx.xxx] bash: line 8: syntax error near unexpected token `('
  [xx.xxx.xx.xxx] bash: line 8: `DIST....: CentOS Linux release 7.9.2009 (Core)'
  [xx.xxx.xx.xxx]  error  in update_code.php on line 73:
  [xx.xxx.xx.xxx] exit code -1 (Unknown error)
  ::group::task deploy:failed
task deploy:failed
::group::task deploy:unlock
task deploy:unlock
Error: Process completed with exit code 255.
```

### .github/workflows/deploy.yml
```yaml

      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.ENV_PRODUCTION }}
          LANG: en_GB.utf8
        run: ./vendor/bin/dep deploy stage=prod --tag=${{ env.GITHUB_REF }} -vvv
```

### deploy.php
```php
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/rsync.php';

// Project name
set('application', 'theappname');
set('ssh_multiplexing', true);

set('rsync_src', function () {
	return __DIR__;
});

add('rsync', [
	'exclude' => [
		'.git',
		'/.env',
		'/storage/',
		'/vendor/',
		'/node_modules/',
		'.github',
		'deploy.php',
	],
]);

task('deploy:secrets', function () {
	file_put_contents(__DIR__ . '/.env', getenv('DOT_ENV'));
	upload('.env', get('deploy_path') . '/shared');
});

host('xx.xxx.xx.xxx')
	->set('labels', ['stage' => 'prod'])
	->set('port', xxx)
	->setRemoteUser('myuser') // SSH user
	->setDeployPath('/home/myuser');

after('deploy:failed', 'deploy:unlock');

desc('Deploy the application');
task('deploy', [
	'deploy:info',
	'deploy:prepare',
	'deploy:lock',
	'deploy:release',
	'rsync', // Deploy code & built assets
	'deploy:secrets',
	'deploy:shared',
	'deploy:vendors',
	'deploy:writable',
	'artisan:storage:link', // |
	'artisan:view:cache',   // |
	'artisan:config:cache', // | Laravel specific steps
	'artisan:optimize',     // |
	'artisan:migrate',      // |
	'deploy:symlink',
	'deploy:unlock',
	'deploy:cleanup',
]);
```

I figure there's something wrong in my deploy.php file, but I can't find what's going wrong. The line referenced in update_code.php seems to be something to do with `$repository = get('repository');` but I'm not sure if it's relevant.
