### DISCUSSION TITLE
Is it possible add() functionality in yaml (import())? v7

### DISCUSSION THREAD

**Discussion by Kayu84** [deployphp/deployer#3037] [Help needed]
Hello,
maybe you can answer my question please?
(deployer v7)
Is it possible to import() the add() funktionality?
I tried to import() a config.yml.
But this overwrites previously set() configurations…
I also tried to add add: in different places (like run()) without success…
```
config:
  add:
    shared_files:
      - .env
config:
  shared_files:
    add:
      - .env
config:
  shared_files:
    - add: .env
```
