### DISCUSSION TITLE
Add --no-dev option to composer

### DISCUSSION THREAD

**Discussion by hashimaziz1** [deployphp/deployer#3075] [Help needed]
I'm trying to solve a server permissions issue between Deployer and Clockwork, and the easiest solution to it seems to be to install Clockwork as a dev dependency and then run `composer --no-dev` on the production server. However, I can't work out how to do this in YAML syntax.

Here's my current and otherwise functional `deploy.yaml`:

```
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: "PROJECT_NAME"
  repository: "GITHUB_REPO"
  php_fpm_version: "8.0"
  ssh_multiplexing: false

hosts:
  prod:
    remote_user: hashim
    hostname: DOMAIN_NAME
    deploy_path: "/var/www/{{hostname}}"
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
  npm:run:prod:
    - run: "cd {{release_or_current_path}} && npm run prod"

after:
  deploy:failed: deploy:unlock
```
