### DISCUSSION TITLE
How to specify 'verbose' in task YAML?

### DISCUSSION THREAD

**Discussion by windbridges** [deployphp/deployer#3185] [Help needed]
How to specify 'verbose' in task YAML? This doesn't work:
```
tasks:
  foo:
    - verbose: true
    - desc: Show something
    - cd: '{{deploy_path}}'
    - run: something
```
