### DISCUSSION TITLE
Error: '...repo' does not exist

### DISCUSSION THREAD

**Discussion by acharseth** [deployphp/deployer#3214] [Help needed] [answered]
I am new to Deployer.

I have the following (anonymized) deploy.yaml:
```
import: 
  - recipe/laravel.php

config:
  repository: ''

hosts:
  foo.no:
    remote_user: bar
    deploy_path: '~/www/testdeploy/test'

tasks:
  build:
    - cd: '{{release_path}}'
    - run: 'whoami'

after:
  deploy:failed: deploy:unlock
```

When running `dep deploy`I get the following (anonymized) error message:

```
task deploy:lock
task deploy:release
task deploy:update_code
[foo.no]  error  in update_code.php on line 88:
[foo.no] run export GIT_TERMINAL_PROMPT='0' GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new'; [ -f ~/www/testdeploy/test/.dep/repo/HEAD ] || /usr/bin/git clone --mirror  ~/www/testdeploy/test/.dep/repo 2>&1
[foo.no] fatal: repository '/home/2/l/foo/www/testdeploy/test/.dep/repo' does not exist
[foo.no] exit code 128 (Invalid exit argument)
task deploy:failed
task deploy:unloc
```

I develop locally on my laptop, using git, but no remote repository (not using GitHub or other git-severs).
The folder `.../.dep/repo`does exist.
I get the same error message if I run the same (`/usr/bin/git clone --mirror  ~/www/testdeploy/test/.dep/repo 2>&1`) command on the server inside the `.../.dep/repo` folder.

What am I doing wrong?
