### DISCUSSION TITLE
What happened to the argument function, and with what should we replace it?

### DISCUSSION THREAD

**Discussion by dingo-d** [deployphp/deployer#3226] [Help needed]
I used to deploy things on GH Actions like:

```yaml
...
      - name: Deploy application to staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          admin_user: ${{ secrets.ADMIN_USER }}
          admin_email: ${{ secrets.ADMIN_EMAIL }}
          admin_password: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          deployer deploy "$admin_user" "$admin_email" "$admin_password" staging
```

where I could get the arguments using:

```php
argument('admin_user', InputArgument::REQUIRED, 'WP admin username.');
...
```

From what I've searched, the `argument` function no longer exists, so should I use `$GLOBALS['argv']` instead, or is there a replacement function for fetching CLI arguments?
