### DISCUSSION TITLE
6 to 7 upgrade: can no longer use inventory()

### DISCUSSION THREAD

**Discussion by awtg-elmer** [deployphp/deployer#3250] [Help needed]
I am currently working on a WordPress project that still uses v6 and now failing the build.
It can accommodate multistage[dev, test, main] branches previously.
At the moment, our project still uses **inventory( )**. I found [upgrade documentation](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md) but I am not sure if in step.7 if it's the sample "deploy.yaml". 

If so, how do we configure it for multi-environment? 
Below is the current deploy.yaml that's being called in deploy.php  by inventory( 'deploy.yml' );

**_deploy.yml_**
`.base: &base
  hostname: hostname
  user: deployer
  application: appname
  repository: git@github.com:org/repo.git
  deploy_path: /var/www/html/
  branch: main

dev:
  <<: *base
  hostname: xx.xx.xx.x
  stage: dev
  branch: dev

test:
  <<: *base
  hostname: xx.xx.xx.x
  stage: test
  branch: test

main:
  <<: *base
  hostname: xx.xx.xx.x
  stage: main
  branch: main`

**Comment by akosglue** [comment]
I think you need top-level hosts, something like this:

```
.base: &base
  remote_user: app
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: false
  keep_releases: 3
  ssh_arguments: ['-o StrictHostKeyChecking=no','-o UserKnownHostsFile=/dev/null']
hosts:
  master:
    <<: *base
    hostname: xxxx
    deploy_path: ~/sites/xxxx
  staging:
    <<: *base
    hostname: xxxx
    deploy_path: ~/sites/xxxx
  dev:
    <<: *base
    hostname: xxxx
    deploy_path: ~/sites/xxxx
```
