### DISCUSSION TITLE
How to correctly fill in ssh-config in github actions

### DISCUSSION THREAD

**Discussion by tlerbao** [deployphp/deployer#3309] [Help needed]
### According to the following method, an error will be reported: 

**Host key verification failed..**

If ssh-config: ${{ secrets.SSH_CONFIG }} is removed, and the host directly specifies the IP address and port in deploy.php, actions can be executed successfully

### my deployer.yml

```
- name: Deploy
    uses: deployphp/action@v1
    with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        dep: deploy -vvv
        deployer-version: "7.0.2"
        ssh-config: ${{ secrets.SSH_CONFIG }}
```

### ${{ secrets.SSH_CONFIG }}

```
Host TalentServerTokyo
  HostName 43.130.xxx.xxx
  User deployer
  Port 112
```
