### DISCUSSION TITLE
setfacl error while `deploy:writable`: Only directories can have default ACLs

### DISCUSSION THREAD

**Discussion by dakur** [deployphp/deployer#3313] [Help needed]
- Deployer version: 7.0.2
- Deployment OS: Ubuntu 18

When I try to deploy with 7.0.2, it fails with `err setfacl: log/.gitignore: Only directories can have default ACLs`. ~~If I downgrade to 7.0.1, it works.~~ It appeared that it's not about version, but about if I deploy for the first time when no dirs exist yet, or when the directory structure already exists. In first case, it fails, in the second it deploys without problem.

I use setfacl permissions on remote machine.

```php
<?php declare(strict_types = 1);

use function Deployer\{after, desc, import, run, task, upload};


require_once 'recipe/common.php';

import(__DIR__ . '/config.yml');


task('deploy:copy', function () {
	upload('..', '{{release_path}}');
});

task('deploy', [
	'deploy:info',
	'deploy:setup',
	'deploy:lock',
	'deploy:release',

	'deploy:copy_dirs',
	'deploy:copy',

	'deploy:shared',
	'deploy:writable',

	'deploy:symlink',

	'deploy:unlock',
	'deploy:cleanup',
	'deploy:success',
]);

after('deploy:failed', 'deploy:unlock');
```

```yaml
config:
    ssh_type: native
    ssh_multiplexing: true

    remote_user: web-xy-abc
    identityFile: /path/to/key
    deploy_path: /var/www/someplace

    shared_files:
        - config/local.neon

    shared_dirs:
        - log
        - data

    writable_dirs:
        - log
        - temp
        - data


hosts:
    production:
        labels:
            stage: production
        hostname: x.x.x.x

```
