### DISCUSSION TITLE
How to start a long polling process with artisan

### DISCUSSION THREAD

**Discussion by gerrit-sping** [deployphp/deployer#3490] [Help needed]
I have a laravel project that I deploy con github actions to my servers.
after a successful deployment I need to start a long polling process 
`nohup /usr/bin/php artisan tracking:start &`

part of my script is:
```
tasks:
  build:
    - run: "cd {{release_path}}"
    - run: php artisan migrate
    - run: uptime
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - deploy:publish
    - php-fpm:reload
  tracking:
    - run: "nohup /usr/bin/php artisan tracking:start &"

after:
  deploy:failed: deploy:unlock
```

but it does not execute te nohup command

Can anybody help?
