### DISCUSSION TITLE
How to set the description of a task group defined via YAML?

### DISCUSSION THREAD

**Discussion by oliverklee** [deployphp/deployer#3504] [Help needed]
I have this task (group) defined via YAML:

```yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:publish

after:
  deploy:prepare:
    - typo3:create_default_folders
    - typo3:update:databaseschema
    - typo3:flush:caches
    - typo3:setup:extensions
    - typo3:flush:caches

  deploy:failed:
    - deploy:unlock
```

I'm trying to find a way to set the description of this task group so that `deployer dep list` shows a nice description and not only the key of the task.

Is there any way to do this?
