### DISCUSSION TITLE
cannot tail a log, shows nothing, same command on server works

### DISCUSSION THREAD

**Discussion by digitall-it** [deployphp/deployer#3516] [Help needed]
- Deployer version: 7.2.0
- Deployment OS: Ubuntu 22.04 LTS (server) macOS Ventura 13.2.1 on ARM (client) with PHP 8.2.3 (cli)

I can login to server and issue as [USER]
```
tail -f /var/www/shared/storage/logs/nginx_access.log
```
and see the log

but  
```
dep logs:nginx
task logs:nginx
```
shows nothing

a minimal deploy.yaml
```
config:
  repository: [REPOSITORY]

hosts:
  prod:
    hostname: [HOST]
    remote_user: [REMOTE_USER]
    deploy_path: '/var/www'

tasks:

  logs:nginx:
    - run: 'tail -f /var/www/shared/storage/logs/nginx_access.log'
```
