### DISCUSSION TITLE
temporarily ip address as hostname causes no such directory error

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#3565] [Help needed] [answered]
I need temporary ip address only access to set up the server so I use

```
...
hosts:
  prod:
    # hostname: 'site.com'
    # remote_user: forge
    hostname: 'xx.xx.xxx.xx'
    remote_user: ploi
...
```

I do get access but I see this error

```
bash: line 1: cd: /home/ploi/xx.xx.xxx.xx No such file or directory
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```

Is there a correct way to do this?
