### DISCUSSION TITLE
Deployer\Exception\ConfigurationException  in Importer.php on line 93

### DISCUSSION THREAD

**Discussion by AyubTouba** [deployphp/deployer#3593] [Help needed] [answered]
- Deployer version: ^7.3
- Deployment OS: windows/server Ubuntu

```
`import: 
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'xxxx'
  repository: 'git@gitlab.com:xxxxx'
  php_fpm_version: '8.0'

hosts:
  prod:
    remote_user: xxx
    hostname: xxxx
    deploy_path: '~/{{hostname}}'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - php-fpm:reload
  npm:run:prod:
     - script:
       - 'cd {{release_or_current_path}} && npm run prod'

after:
  deploy:failed: deploy:unlock
`
```

When I launch the deploy command on git cli `vendor/bin/dep deploy -o ssh_multiplexing=false` I always get:

> task deploy:info
[prod] info deploying HEAD
task deploy:setup
task deploy:lock
[prod]  Deployer\Exception\GracefulShutdownException  in lock.php on line 14:
[prod]
[prod]   Deploy locked by xxxxx.
[prod]   Execute "deploy:unlock" task to unlock.
[prod]
ERROR: Task deploy:lock failed!

Ps without the `-o ssh_multiplexing=false` I got : 

> `[prod] err mux_client_request_session: read from master failed: Connection reset by peer
> [prod] err Failed to connect to new control master
> [prod] exit code -1 (Unknown error)`
