### DISCUSSION TITLE
How to define multiple hosts (web servers) in hosts.yml inventory version 6.8.0

### DISCUSSION THREAD

**Discussion by marketier** [deployphp/deployer#3611] [Help needed]
I'm using PHP Deployer 6.8.0. I have multiple hosts (web servers) per environment. How do I define this in hosts.yml? The following returns an array error.

```
hosts:
    uat:
        hostname: 
		  - 10.20.30.50
        remote_user: someuser
        port: 22
        forwardAgent: true
        multiplexing: true
        ssh_arguments: ['-o UserKnownHostsFile=/dev/null','-o StrictHostKeyChecking=no']
        stage: production
        deploy_path: "/var/www/vhosts/mywebapp/"
		
    production:
        hostname: 
		  - 10.20.30.40
		  - 10.20.30.41
		  - 10.20.30.42
        remote_user: someuser
        port: 22
        forwardAgent: true
        multiplexing: true
        ssh_arguments: ['-o UserKnownHostsFile=/dev/null','-o StrictHostKeyChecking=no']
        stage: production
        deploy_path: "/var/www/vhosts/mywebapp/"
```
