### DISCUSSION TITLE
Always getting asked for password

### DISCUSSION THREAD

**Discussion by ps-20x** [deployphp/deployer#3625] [Help needed] [answered]
I am having a problem that the ssh connection is for any reason always asking for the password.
> Permission denied (publickey,password)

### Steps what I have done
* Created an ssh key (`ed25519`)
* Added the private key to GitHub secrets in `SSH_PRIVATE_KEY`
* ssh to the server and add the public key to `authorized_keys`

<details>
  <summary>My github workflow looks like</summary>

```yml
name: Deploy

on:
    push:
        branches: [ develop ]
    pull_request:

concurrency: deploy_staging

jobs:
    deploy-api-staging:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./api

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.ref }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.2"

            -   name: Install dependencies
                run: composer install

            -   name: Deploy
                uses: deployphp/action@v1
                with:
                    dep: --file=api/deploy.yaml deploy
                    private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                    ssh-config: |
                        Host *
                          StrictHostKeyChecking no
                    skip-ssh-setup: false
                    deployer-binary: "api/vendor/bin/dep"
                    verbosity: -vvv
```
</details>

<details>
  <summary>My config for deployer looks like</summary>

I replaced `{{company}}`, `{{project}}`, `{{host}}` here for the question
```yml
import:
    - recipe/laravel.php

config:
    repository: 'git@github.com:{{company}}/{{project}}.git'

hosts:
    {{host}}:
        stage: staging
        remote_user: my_user
        user: my_user
        deploy_path: '~/{{project}}/api'
        forward_agent: false

tasks:
    build:
        -   run: pwd
        -   run: uptime

after:
    deploy:failed: deploy:unlock
```
</details>

For the moment the deploy is not really doing anything but I will update that later on. At the moment I am stuck with accessing the server without password. Does anyone have an idea on how to solve that?
