### DISCUSSION TITLE
GitLab runner, how to deploy changes to `deploy.php` ?

### DISCUSSION THREAD

**Discussion by nbennett25** [deployphp/deployer#3702] [Help needed]
I have a server set up with a GitLab runner, connected to a repository containing the `deployer/deployer` package, and a super basic recipe. 

When code is pushed to the repository, it kicks off a GitLab pipeline and deploys the code to the server as `localhost` rather than a remote; but how do I tell the `vendor/bin/dep deploy` command to use an updated version of `deploy.php`? 

for example:

```
deploy:
  stage: deploy
  tags:
    - deployer-testing
  script:
    - cd /var/www/html/current && vendor/bin/dep deploy -vvv
  environment: development
```

When deployer runs, it goes to the doc root and runs `vendor/bin/dep deploy` - works as expected, but it's using whatever version of `deploy.php` is in the _current_ release, not the one in the new code.

Is there a work around to pull the `deploy.php` before running the `vendor/bin/dep` command...? 

(Maybe I'm going about this all wrong..?)
