### DISCUSSION TITLE
npm run prod not firing

### DISCUSSION THREAD

**Discussion by jasperf** [deployphp/deployer#3744] [Help needed] [answered]
Using 
```
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php
...
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - deploy:publish
  npm:run:prod:
    - run: 'cd {{release_path}} && npm run prod'
...
   ```

but it does not seem to run and we get no feedback on that task. How to run npm run prod and how to get feedback?

**Comment by jasperf** [comment]
Used
```
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:run:prod
    - deploy:publish
    - artisan:horizon:terminate
  npm:run:prod:
    - run: 'cd {{release_path}} && npm run prod'
```

and that did run but then I got

```
[staging]  error  in deploy.yml on line 70:
[staging] run cd ~/staging.site.com/releases/60 && npm run prod
[staging] err sh: 1: mix: not found
[staging] err npm notice
[staging] err npm notice New major version of npm available! 9.6.7 -> 10.2.5
[staging] err npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
[staging] err npm notice Run `npm install -g npm@10.2.5` to update!
[staging] err npm notice
[staging] > prod
[staging] > npm run production
[staging] > production
[staging] > mix --production
[staging] exit code 127 (Command not found)
ERROR: Task npm:run:prod failed!
task deploy:failed
task deploy:unlock
```

**Comment by jasperf** [comment, marked as answer]
This did run
```
...
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - artisan:horizon:terminate
  npm:run:prod:
    - run: 'cd {{release_or_current_path}} && npm run prod'
...
```
