### DISCUSSION TITLE
Host specific tasks: on() and select() in YAML?

### DISCUSSION THREAD

**Discussion by wivaku** [deployphp/deployer#3785] [Help needed] [answered]
I can use on() and select() to run specific tasks on specific hosts.
https://deployer.org/docs/7.x/selector#using-the-select-function

Can I configure tasks like that in a YAML based setup?

**Comment by wivaku** [comment, marked as answer]
While checking the [JSON Schema](https://raw.githubusercontent.com/deployphp/deployer/master/src/schema.json), I noticed `select` is available. But it expects a string, which based on my test expects a **single hostname** (as opposed to the PHP version where you provide a filter, e.g. `$hosts = select('type=web,env=prod');`)

So e.g.
```
hosts:
  production:
    # ...
  staging:
    # ...

tasks:
  mytask:
    - select: production
    # - cd: ...
    # - run: ...
```

The schema lists as possible properties: 
- string: `cd`, `run`, `run_locally`, `desc`
- object: `upload`, `download`
- boolean: `once`, `hidden`
- number: `limit`
