### DISCUSSION TITLE
How to store Sentry token

### DISCUSSION THREAD

**Discussion by kouinkouin** [deployphp/deployer#3858] [Help needed]
Hello,

I just added contrib/sentry.php and that works fine, thanks!

Now, I want to commit that, but where to store the token (token must not be commited)?

I tried that, but deployer does not agree:

deploy.yaml (versionned)
```yaml
import:
  - recipe/symfony.php
  - contrib/sentry.php
  - deploy_secrets.yaml

config:
#...
  sentry:
    organization: xxx-xxxxxx
    projects:
      - xxxxxxx-xxxxx
    git_version_command: "git describe --tags --abbrev=0"
    #< deploy_secrets.yaml
    # token: ******
    #> deploy_secrets.yaml
```

deploy_secrets.yaml (git-ignored)
```yaml
config:
#...
  sentry:
    token: sntryu_000000000000000000000000000000000000000000000000000000000000000
```

Result:
```
task deploy:sentry
[staging]  RuntimeException  in sentry.php on line 100:
[staging]
[staging]   Required data missing. Please configure sentry:
[staging]   set(
[staging]   'sentry',
[staging]   [
[staging]   'organization' => 'exampleorg',
[staging]   'projects' => [
[staging]   'exampleproj',
[staging]   'exampleproje2'
[staging]   ],
[staging]   'token' => 'd47828...',
[staging]   ]
[staging]   );"
[staging]
ERROR: Task deploy:sentry failed!
```

Thanks for your ideas!

**Comment by antonmedv** [comment]
I think in the .env file is the best way.

**Comment by kouinkouin** [comment]
Hi,
Thanks for your answer, but I don't see where store the sentry token in the .env .
You mean by adding a SENTRY_TOKEN (or another name) in the .env of the deployed application, the task deploy:sentry will retrieve the token?

I tried that too:
deploy.yaml:
```yaml
import:
...
  - contrib/sentry.php
  - deploy_secrets.php

config:
...
  sentry:
    organization: xxx-xxxxxx
    projects:
      - xxxxxxx-xxxxx
    git_version_command: "git describe --tags"
    #< deploy_secrets.php
    token: "{{secret_sentry_token}}"
    #> deploy_secrets.php

after:
...
  deploy: deploy:sentry
```

deploy_secrets.php, which is not versioned:
```php
<?php

namespace Deployer;

set('secret_sentry_token', 'sntryu_000000000000000000000000000000000000000000000000000000000000000');
```

But I receive a:
```
task deploy:sentry
[staging]  RuntimeException  in sentry.php on line 140:
[staging]
[staging]   Unable to create a release: Array
[staging]   (
[staging]   [detail] => Invalid token
[staging]   )
[staging]
ERROR: Task deploy:sentry failed!
```

I guess the inclusion pf the token variable is wrong, but I don't know why :thinking:
