### DISCUSSION TITLE
merge yaml config section and host config

### DISCUSSION THREAD

**Discussion by huiyang** [deployphp/deployer#3875] [Help needed]
version of deployer: 7.3.0
I have something like the following in my deploy.yaml file

```
config:
  directadmin:
    domain_name: example.com

hosts:
  host1:
    directadmin:
      db_name: host1_db
```

i expect both "directadmin" sections will be merge when i get('directadmin') under host1 execution, but it have only have db_name key in $config['directadmin'].

how can i merge them? is that possible? 
(i have like 10 hosts, so not prefer to copy the whole section to the host section.)

thanks.
