### DISCUSSION TITLE
ErrorException  in BaseConstraint.php on line 46:   Optional parameter $path declared before required parameter $message is implicitly treated as a required parameter

### DISCUSSION THREAD

**Discussion by avenit-jke** [deployphp/deployer#3967] [Bugs] [answered]
### Deployer Version

v7.5.6

### Target OS

FreeBSD 14

### Which PHP version are you using?

PHP 8.1

### Content of deploy.php or deploy.yaml

```
import:
  - recipe/typo3.php
  - contrib/rsync.php

config:
  repository: '.'
  typo3_webroot: 'public'
  rsync:
    exclude-file: false
    include: {  }
    include-file: false
    filter: {  }
    filter-file: false
    filter-perdir: false
    flags: rz
    options: [delete, keep-dirlinks, links]
    timeout: 600
  shared_dirs:
    - ...
  shared_files:
    - ...
  writable_mode: 'chmod'
  writable_dirs: [ '{{typo3_webroot}}/fileadmin', '{{typo3_webroot}}/typo3temp', '{{typo3_webroot}}/typo3conf', '{{typo3_webroot}}/uploads', 'var' ]

hosts:
  production:
    hostname: 'example.com'
    remote_user: 'username'
    deploy_path: '/var/www/typo3'
    rsync_src: './'
    php_version: '8.1'

tasks:
  typo3:extension:setup:
    - cd: '{{release_path}}'
    - run: 'vendor/bin/typo3cms install:extensionsetupifpossible'
  typo3:cache:warmup:
    - cd: '{{release_path}}'
    - run: 'vendor/bin/typo3 cache:warmup'
  typo3:cache:flush:
    - cd: '{{release_path}}'
    - run: 'vendor/bin/typo3 cache:flush'

  deploy:
    - deploy:info
    - deploy:setup
    - deploy:lock
    - deploy:release
    - rsync
    - deploy:shared
    - deploy:writable
    - deploy:symlink
    - typo3:extension:setup
    - typo3:cache:flush
    - typo3:cache:warmup
    - deploy:unlock
    - deploy:cleanup
    - deploy:success

after:
  deploy:failed: deploy:unlock
```

### Steps to reproduce

Try to deploy with deployer 7.5.6 to PHP 8.1.
Deployer 7.5.5 still works.

Error Message:
```
+ dep deploy -vvv production
 ErrorException  in BaseConstraint.php on line 46:
  Optional parameter $path declared before required parameter $message is implicitly treated as a required parameter
#0 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(444): {closure}(8192, 'Optional parame...', 'phar:///root/.c...', 46)
#1 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(444): include()
#2 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///root/.c...')
#3 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(23): Composer\Autoload\ClassLoader->loadClass('JsonSchema\\Cons...')
#4 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(444): include('phar:///root/.c...')
#5 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///root/.c...')
#6 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/src/Importer/Importer.php(90): Composer\Autoload\ClassLoader->loadClass('JsonSchema\\Vali...')
#7 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/src/Deployer.php(314): Deployer\Importer\Importer::import(Array)
#8 phar:///root/.config/composer/vendor/deployer/deployer/bin/dep/bin/dep(96): Deployer\Deployer::run('7.5.6', '/opt/atlassian/...')
#9 /root/.config/composer/vendor/deployer/deployer/bin/dep(4): require('phar:///root/.c...')
#10 /root/.config/composer/vendor/bin/dep(119): include('/root/.config/c...')
#11 {main}
```
