### DISCUSSION TITLE
"Select hosts" prompt is still displayed while executing a task that has it's host set via select

### DISCUSSION THREAD

**Discussion by kodie** [deployphp/deployer#3977] [Bugs]
### Deployer Version

v7.5.8

### Target OS

Ubuntu 24.04

### Which PHP version are you using?

PHP 8.2.26

### Content of deploy.php or deploy.yaml

`deploy.yml`:

```yml
config:
  application: my-website
  repository: git@github.com:my-github/{{application}}.git
  current_path: /srv/users/web/apps/{{application}}/public
  deploy_path: /srv/users/web/apps/{{application}}/public_html
  bin/composer: /usr/bin/composer
  use_atomic_symlink: false

hosts:
  localhost:
    labels:
      stage: development

  staging:
    hostname: 123.456.789.100
    remote_user: web
    branch: development
    labels:
      stage: staging

  production:
    hostname: 123.456.789.100
    remote_user: web
    branch: main
    labels:
      stage: production
```

`deploy.php`:

```php
task('my:func', function () {
  echo 'You would think that this would not prompt me to select hosts if the host has been selected for me.';
})
  ->once()
  ->select('localhost')
  ->desc('My awesome function');

localhost();
```

### Steps to reproduce

Have `deploy.yml` and `deploy.php` set up as I do and run `dep my:func` and you'll see that it prompts you to select your hosts even though the `select` function is used and set to `localhost` so I'd expect to not be prompted.

What's weird is when you're prompted and select any host other than "localhost", it says "Done" and freezes where I have to Ctrl+C out to be able to do anything. If you select "localhost" every runs fine and as expected.

This also works if I change the parameter in the `select` function to something like "staging", if I run the task and select anything else other than "staging", it freezes, if I select "staging", it runs fine.
