### DISCUSSION TITLE
Http call with a proxy

### DISCUSSION THREAD

**Discussion by adpeyre** [deployphp/deployer#4035] [Help needed]
Hi,
I use the sentry contrib but the used Httpie does not use my proxy. Is it possible to define it ?
https://github.com/deployphp/deployer/blob/master/contrib/sentry.php 

Ty

**Comment by antonmedv** [comment]
Yes. how do you define your proxy?

**Reply by adpeyre** [reply]
I tried to use :
``` yaml
config:
    env:
        https_proxy: http://proxy-eolas-vrouter.eolas-services.com:3128
```

This configuration works for my tasks but not for local http calls.

The http_proxy variable is not defined globally and I would like to avoid doing so.
A solution could be `https_proxy=xxxx && ./dep xxx` but it's not very pretty.
