### ISSUE TITLE
Role, tag or group

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#1099]
I think to add new functionality to group hosts info bunches. What name to use for it? 
* role
* tag
* group

**Comment by staabm** [comment]
`hostgroup` ?

**Comment by elfet** [comment]
Example:

```php
host('domain.com')
    ->tag('app');

host('db.domain.com')
    ->tag('db');
```

Or in yml:

```yaml
domain.com:
  tag: app
db.domain.com
  tag: db
```

In deploy.php:

```php
task('migrate', 'db migrate')
    ->on('db');
```

**Comment by elfet** [comment]
Also i think to deprecate all task method `onlyOn`, `onlyOnStage` and leave only one method `on`.

Each host will have this properties:
* hostname _string_
* stage _string_
* tags _string[]_

For example:
```
host('host1')
    ->tag('app')
    ->set('stage', 'production');

host('host2')
    ->tag('db')
    ->set('stage', 'production');

host('host3')
    ->tag('app', 'db')
    ->set('stage', 'beta');
```

Now task with filtering `on('production')` will be executed only on _host1_ and _host2_. 
With `on('db')` only on _host2_ and _host3_. With `on('host1', 'beta')` will never be executed.

**Comment by elfet** [comment]
Or use **roles**

```php
host('host1')
    ->roles('app')
    ->set('stage', 'production');

host('host2')
    ->roles('db')
    ->set('stage', 'production');

host('host3')
    ->roles('app', 'db')
    ->set('stage', 'beta');
```


```yaml
host1:
  roles: app
  stage: production

host2:
  roles: db
  stage: production

host3: 
  roles
    - app
    - db
  stage: beta
```
