### ISSUE TITLE
Feature Request: Allow setting variables with YAML 

### ISSUE THREAD

**Issue by pryley** [deployphp/deployer#1108]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 4.3.0
| Local Machine OS  | macOS Sierra
| Remote Machine OS | Ubuntu LTS 14.0.1

### Description

It would be great to allow overriding or setting options with yaml like you can do for the server settings.

Here is an example `config.yml`:
```yml
application: myapp
default_stage: staging
deploy_path: /srv/users/serverpilot/apps/myapp
keep_releases: 5
local_uploads_dir: /Users/me/Sites/myapp/app/uploads
local_url: myapp.dev
public_dir: public
repository: git@github.com/myapps/myapp.git
rsync_options: -avz --progress -e 'ssh -p {{server.port}}' --exclude=temp/
shared_dirs:
    - app/uploads
shared_files:
    - public/.htaccess
    - public/robots.txt
ssh_multiplexing: true
ssh_type: native
uploads_dir: shared/app/uploads
writable_dirs:
    - app/uploads
```

The function could look something like this:

```php
namespace Deployer;

use Symfony\Component\Yaml\Yaml;

/**
 * @return void
 * @throws \RuntimeException
 */
function configList( $file ) {
    $configFileContent = Yaml::parse( file_get_contents( $file ));

    if( !is_array( $configFileContent )) {
        throw new \RuntimeException( "Error in parsing " . $file . " file." );
    }
    foreach( $configFileContent as $key => $value ) {
        set( $key, $value );
    }
}
```

And you could load both the deployer servers and config like this:

```php
configList( 'config.yml' );
serverList( 'server.yml' );
```
