### ISSUE TITLE
SSH connection seems to be closed/opened for each command

### ISSUE THREAD

**Issue by winzou** [deployphp/deployer#1187]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug/Question
| Deployer Version  | 5.0@beta2
| Local Machine OS  | Windows 10
| Remote Machine OS | Debian Squeeze

### Description 
It seems that the SSH connection is closed and reopened for each command sent to the server.
I can see the `ssh multiplexing initialization` and `Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.` between each command.

It's the same if a disable ssh multiplexing, I still have the `Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.` between each command.

**=> The consequence is that it is super super slow to execute!**

### Steps to reproduce
Just execute a task with 2 or more commands to be sent to the server.

### Content of `hosts.yml`
```yaml
dev:
  hostname: 1.2.3.4
  user: travelblogs
  identityFile: "/C/Users/alex/.ssh/github_rsa"
  stage: dev
  deploy_path: ~/dev
  options:
    - "UserKnownHostsFile=/dev/null"
    - "StrictHostKeyChecking=no"
```

### Output log

    ➤ Executing task deploy:shared
    [1.2.3.4] > if [ -d ~/dev/shared/var/logs ]; then echo 'true'; fi
    [1.2.3.4] < ssh multiplexing initialization
    [1.2.3.4] < Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
    [1.2.3.4] > mkdir -p ~/dev/shared/var/logs
    [1.2.3.4] < ssh multiplexing initialization
    [1.2.3.4] < Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
    [1.2.3.4] > if [ -d $(echo ~/dev/releases/1/var/logs) ]; then echo 'true'; fi
    [1.2.3.4] < ssh multiplexing initialization
    [1.2.3.4] < Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
    [1.2.3.4] < true
    [1.2.3.4] > cp -rv ~/dev/releases/1/var/logs ~/dev/shared/var
    [1.2.3.4] < ssh multiplexing initialization
    [1.2.3.4] < Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
    [1.2.3.4] < « /home/travelblogs/dev/releases/1/var/logs/.gitkeep » -> « /home/travelblogs/dev/shared/var/logs/.gitkeep »
