### ISSUE TITLE
Deployer ignores every but last host set in YAML config

### ISSUE THREAD

**Issue by dakur** [deployphp/deployer#1229]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.0
| Local Machine OS  | Ubuntu 14.04.5 LTS, Ubuntu 16.04.2 LTS
| Remote Machine OS | Ubuntu 14.04.5 LTS

### Description 
If I deploy to `development` with settings below, it fails with `Hostname or stage "development" was not found.` If I deploy to `production`, it works. If I set up the deploy with PHP functions (`set`, `host` etc.), it works.

### Steps to reproduce
Set your deployer like this:
```
.deploy-template: &deploy-template
    ssh_type: native
    ssh_multiplexing: true

    hostname: 10.0.0.2
    user: someuser
    port: 22
    identityFile: /root/.ssh/id_rsa


development:
    <<: *deploy-template
    stage: development
    deploy_path: /var/www/web/dev

production:
    <<: *deploy-template
    stage: production
    deploy_path: /var/www/web/www
```

Run: `dep deploy development` and `dep deploy production`

### Content of `deploy.php`
```php
<?php

namespace Deployer;


/** @noinspection PhpIncludeInspection recipe comes from Deployer tool */
require_once 'recipe/common.php';

// deploy stages settings
inventory(__DIR__ . '/config.yml');


// task
task('deploy:copy', function () {
	upload('../dist/', '{{release_path}}');
});


// deploy process
desc('Deploy your project');
task('deploy', [
	'deploy:prepare', // checks env and prepares folder for new release
	'deploy:lock',
	'deploy:release',

	'deploy:copy',

	'deploy:symlink', // swap to current release

	'deploy:unlock',
	'cleanup', // remove old releases
	'success',
]);

// automatically unlock if deploy fails
after('deploy:failed', 'deploy:unlock');
```

### Output log
```
[Deployer\Exception\Exception]                  
  Hostname or stage `development` was not found.  
                                                  

Exception trace:
 () at /root/.composer/vendor/deployer/deployer/src/Host/HostSelector.php:59
 Deployer\Host\HostSelector->getHosts() at /root/.composer/vendor/deployer/deployer/src/Console/TaskCommand.php:111
 Deployer\Console\TaskCommand->execute() at /root/.composer/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /root/.composer/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at /root/.composer/vendor/deployer/deployer/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at /root/.composer/vendor/symfony/console/Application.php:190
 Symfony\Component\Console\Application->doRun() at /root/.composer/vendor/symfony/console/Application.php:121
 Symfony\Component\Console\Application->run() at /root/.composer/vendor/deployer/deployer/src/Deployer.php:315
 Deployer\Deployer::run() at /root/.composer/vendor/deployer/deployer/bin/dep:111

```
