### ISSUE TITLE
Deploy server to server

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [deployphp/deployer#1522]
Is it possible by clicking on a button deploy complete word press website to anther hosting server by using deployer ?

**Comment by antonmedv** [comment]
Soon will be.

**Comment by ZaheerAbbasAghani** [comment]
do u have any idea ? from where to start ? if i want to achieve this type of task to be done.

**Comment by ZaheerAbbasAghani** [comment]
and when i am adding below script in cmd showing an error 'mv' is not recognized as internal or external commad,operable program or batch file.

curl -LO https://deployer.org/deployer.phar
mv deployer.phar /usr/local/bin/dep
chmod +x /usr/local/bin/dep

**Comment by cafferata** [comment]
Hi @naffiq, I discovered that you're using the latest `deployer.phar` instead of a semantic version Deployer binary. Our solution/steps for a Deployer deployment through Gitlab CI:

Install, as an example, an (older) version Deployer

```
composer require --dev deployer/deployer 6.0.5
```

Configure Gitlab CI, and use the Deployer binary `./vendor/bin/dep`

```
before_script:
    - composer config cache-dir /cache/.composer/cache --global
    - composer install --prefer-dist --no-progress --optimize-autoloader --no-interaction

cache:
    paths:
      - vendor/

stages:
    - deploy

acc-release:
    image: jcid/php:7.2
    stage: deploy
    only: [env/acc]
    when: on_success
    script: ./vendor/bin/dep deploy acc --no-ansi --no-interaction

prod-release:
    image: jcid/php:7.2
    stage: deploy
    only: [master]
    when: manual
    allow_failure: false
    script: ./vendor/bin/dep deploy prod --no-ansi --no-interaction
```
