### ISSUE TITLE
How to handle a server load-balanced and one-site-multiple-deployment scenario?

### ISSUE THREAD

**Issue by dareenzo** [deployphp/deployer#1530]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.5
| Local Machine OS  | Mac OS X
| Remote Machine OS | Ubuntu

### Description 

I'd like help in handling the following scenario:

- 4 sites
- 2 load-balanced servers. Each site is on both servers
- 2 stages for each site (production and staging). Also on both servers
- 1 git repository

I would like to able to:

- deploy to 1 site on a specific stage on both hosts.
- deploy to all sites on a specific stage on both hosts.

NOTE:
- each site is just a deployment of the same app with customized configurations for colorings, languages and meant to handle a different region. Something like StackExchange network

Thanks

**Comment by antonmedv** [comment]
First describe your inventory.
For example:
```
host1_site1_stageing:
    hostname: host1.com
    deploy_path: ~/site1_staging
host1_site1_production:
    hostname: host1.com
    deploy_path: ~/site1_production
host2_site1_stageing:
    hostname: host2.com
    deploy_path: ~/site1_staging
host2_site1_production:
    hostname: host2.com
    deploy_path: ~/site1_production
```

Same for second one (use yaml refs). 

Organize hosts into stages and roles. (for example roles can be: `['site1', 'site2']`)
