### ISSUE TITLE
Branch override not working with hosts.yml

### ISSUE THREAD

**Issue by joelpittet** [deployphp/deployer#1697]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | dev-master (6.x)
| Local Machine OS  | OSX
| Remote Machine OS | RHEL

### Description 
Override options in the CLI doesn't seem to override hosts.yml
`branch: develop` seems to be used regardless of what I add to 

### Steps to reproduce
Config like below and tried a number of overrides:
```
./vendor/bin/dep deploy --branch="feature/redirect"
./vendor/bin/dep deploy --branch=feature/redirect
./vendor/bin/dep deploy --branch=master
./vendor/bin/dep deploy -o branch="feature/redirect"
./vendor/bin/dep deploy -o branch=master
```

### Content of `deploy.php`

```yaml
.base: &base
  user: user
  multiplexing: true
  deploy_path: /var/www/{{application}}
  branch: master

staging:
  <<: *base
  hostname: stg.site.example.com
  stage: staging
  branch: develop

...

```
```php
<?php

namespace Deployer;

require_once 'recipe/common.php';

// Project name.
set('application', 'site');

// Hosts.
inventory('hosts.yml');
set('default_stage', 'staging');

// Project repository.
set('repository', 'ssh://git@example.com/site.git');

// [Optional] Allocate tty for git clone. Default value is false.
set('git_tty', TRUE);
set('allow_anonymous_stats', FALSE);

$user_files = [
  'public/sites/default/files',
  'private',
];
set('shared_dirs', $user_files);
set('writable_dirs', $user_files);

set('shared_files', [
  'public/sites/default/settings.local.php',
]);

task('deploy', [
  'deploy:info',
  'deploy:prepare',
  'deploy:lock',
  'deploy:release',
  'deploy:update_code',
  'deploy:shared',
  'deploy:vendors',
  'deploy:symlink',
  'deploy:unlock',
  'cleanup',
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
```
[ feature/redirect ] $ ./vendor/bin/dep deploy -vvv --branch="feature/redirect"
✈︎ Deploying develop on stg.site.example.com
• done on [staging]
```
