### ISSUE TITLE
Gitlab CI: TTY mode requires /dev/tty to be read/writable.  

### ISSUE THREAD

**Issue by sweebee** [deployphp/deployer#1713]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.3.0
| Local Machine OS  | Gitlab CI/docker
| Remote Machine OS | Ubuntu 18

### Description 
I'm getting an error when deploying with GitlabCI:

```
➤ Executing task deploy:prepare
✔ Ok
➤ Executing task deploy:lock
✔ Ok
➤ Executing task deploy:release
✔ Ok
➤ Executing task deploy:update_code
➤ Executing task deploy:failed
✔ Ok
➤ Executing task deploy:unlock
✔ Ok

In Process.php line 1042:
                                                   
  TTY mode requires /dev/tty to be read/writable.  
                                                   

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

ERROR: Job failed: exit code 1
```

### Steps to reproduce

this is my gitlab-ci.yml file:
```
.deploy: &deploy_definition
  stage: deploy
  image: w0rddriven/docker-laravel-deployer
  before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - chmod 600 ~/.ssh/id_rsa
  script:

deploy:develop:
  <<: *deploy_definition
  script:
  - dep deploy develop
  only:
  - develop
```

How to fix this?
