### ISSUE TITLE
Deployer kills it self after echo $0

### ISSUE THREAD

**Issue by flaver12** [deployphp/deployer#1746]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | v6.0.5
| Local Machine OS  | Mac 10.14
| Remote Machine OS |  SMP Debian 4.9.88

### Description 
I try to setup a deployment but  it seams that a the first response of the
server, the deployer fails and I don't see a error. Thx for any help 

### Steps to reproduce
Running: composer run dep deploy haserver --timeout=900 -- --branch=my-cool-branch -vvv 

### Content of `deploy.php`
```php
namespace Deployer;

inventory('deploy.yaml');

require 'vendor/xxxx/deployer-recipes/recipe/speedcurve.php';
require 'vendor/xxxx/deployer-recipes/recipe/varnish.php';
require 'vendor/xxxx/deployer-recipes/recipe/check.php';
require 'vendor/xxxx/deployer-recipes/recipe/common.php';
require 'vendor/xxxx/deployer-recipes/recipe/npm.php';

set('bin/php', '/opt/php7.0/bin/php');

before('deploy:prepare', 'check:branch');
before('deploy:prepare', 'check:tag');
after('deploy:vendors', 'npm');
before('success', 'varnish:purge');
after('success', 'speedcurve:deploy');
```
deploy.yaml
```yaml
.base: &base
    hostname: xx.xxx.xxx.xxx
    user: my_admin_user
    port: 22
    forwardAgent: true
    multiplexing: true
    repository: git@my-git.com/my-repo.git
    speedcurve_api_key:xxxxxx
    speedcurve_site_id: xxxxx
    shared_files:
        - .env
        - public_html/sitemap.xml
    copy_dirs:
        - vendor
        - node_modules
    shared_dirs:
        - public_html/assets/temp
        - system/user/cache/ansel_persistent
        - public_html/stashCache
        - public_html/assets/images/avatars
        - public_html/news-sitemap.xml
    writable_dirs:
        - system/user/cache

staging:
    <<: *base
    stage: staging
    branch: develop
    deploy_path: ~/web/site/staging

production:
    <<: *base
    stage: production
    deploy_path: ~/web/site/production
    varnish_purge_url: http://my-cool-site.test.*

testing:
    <<: *base
    stage: testing
    deploy_path: ~/web/site/testing

testing2:
    <<: *base
    stage: testing2
    deploy_path: ~/web/site/testing2

haserver:
    <<: *base
    hostname: xx.xxx.xxx.xxx
    stage: haserver
    deploy_path: ~/web/site/haserver
```
### Output log
*With enabled option for verbose output `-vvv`.*
```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/flaver/Develop/Work/my-project): git branch --no-color --no-abbrev -v
Reading /Users/flaver/.composer/composer.json
Loading config file /Users/flaver/.composer/composer.json
Reading /Users/flaver/Develop/Work/my-project/vendor/composer/installed.json
Reading /Users/flaver/.composer/vendor/composer/installed.json
Running 1.6.5 (2018-05-04 11:44:59) with PHP 7.2.6 on Darwin / 18.0.0
> dep: dep 'deploy' 'haserver' '--branch=my-cool-branch' '-vvv'
Executing command (CWD): dep 'deploy' 'haserver' '--branch=my-cool-branch' '-vvv'
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < my-cool-branch
✈︎ Deploying my-cool-branch on xx.xxx.xxx.xxx
• done on [haserver]
➤ Executing task deploy:prepare
[haserver] > echo $0
[haserver] < ssh multiplexing initialization
admin-user@xx.xxx.xxx.xxx's password:
[haserver] < bash
➤ Executing task deploy:failed
• done on [haserver]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[haserver] > rm -f ~/web/site/haserver/.dep/deploy.lock

In Client.php line 96:

  [Deployer\Exception\RuntimeException (-1)]
  The command "rm -f ~/web/site/haserver/.dep/deploy.lock" failed.

  Exit Code: -1 (Unknown error)

  Host Name: haserver

  ================
```
