### ISSUE TITLE
Option to use configuration file

### ISSUE THREAD

**Issue by coreyworrell** [deployphp/deployer#1765]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I think a great feature would be to have a single configuration file that has both hosts and configuration. 

This follows the idea of separating configuration from code:
> Apps sometimes store config as constants in the code. This is a violation of twelve-factor, which requires strict separation of config from code. Config varies substantially across deploys, code does not. (https://12factor.net/config)

Config could look like the following:

```yml
repository: git@github.com:user/repo.git
branch: master
shared_dirs:
  - uploads
shared_files:
  - something/file.txt
hosts:
  - user@hostname.com:
      stage: testing
      deploy_path: /var/www/html
  - user@other.com:
      stage: production
      deploy_path: ~/apps/test
      branch: production
```
