### ISSUE TITLE
Set default sshOptions options

### ISSUE THREAD

**Issue by jonnitto** [deployphp/deployer#1892]
How can I set default SSH Options who will be set for every host?

**Comment by antonmedv** [comment]
In for loop for each host.

**Comment by jonnitto** [comment]
Would you be so kind and provide an example?

**Comment by antonmedv** [comment]
for (...) {
   host(...)->setX(...)
}

**Comment by jonnitto** [comment]
The problem is that I would like to run this before the `inventory()`.

**Comment by antonmedv** [comment]
What is the problem your trying to solve?

**Comment by jonnitto** [comment]
I have an inventory YAML file. There are now always the settings 

```yaml
sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
```

These I would like to have set as default
