### ISSUE TITLE
Doctrine migrations not working anymore

### ISSUE THREAD

**Issue by bonswouar** [deployphp/deployer#2207]
### Describe the bug
Doctrine migrations are not working anymore.
It appears that migration paths are now relative to current path.. That's weird but easy fix.

### To reproduce
Update to Doctrine Migration >= 3.0
Example configuration can be found here : https://symfony.com/doc/3.1/bundles/DoctrineMigrationsBundle/index.html#configuration

If I set :
```yml
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': 'src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'

```
I get the error :
> Cannot load migrations from "src/Migrations" because it is not a valid directory

Changing dir before executing the command fixes it.

### Expected behavior
Should execute migrations

### Environment
- Deployer version: 6.2.2
- PHP version: 7.2.33
- Deployment target(s) OS: Debian
