### ISSUE TITLE
Code coverage Github Action

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#2231]
So, it will be cool to have gh action what collects code coverage from unit and e2e tests and reports it in some form. 

NOT integrating third party saas (codecov, etc). 

Somebody wants to implement this?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2231">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2231/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2231/pledge.svg">
</picture>
</a>

**Comment by inverse** [comment]
@antonmedv what's the objections for using a 3rd party for it? Why reinvent the wheel?

**Comment by antonmedv** [comment]
I like to keep things simple. I think it should be fairly easy to implement in GH Actions. But if not 3rd party is okay. 

PS Migrating from https://www.travis-ci.org/ is one of the examples of depending on 3rd party. Now it closing and I have to migrate lots of my project.

**Comment by inverse** [comment]
@antonmedv  Yeah the way Travis did that was kinda a bummer.

However I think integrating something like codecov is very low effort for what you get in return.


```
      - name: Run tests
        run: |
          ./bin/phpunit --coverage-clover coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```
