### ISSUE TITLE
Yaml - Array Syntax vs String Syntax broken

### ISSUE THREAD

**Issue by iBotPeaches** [deployphp/deployer#2509]
- Deployer version: 7beta20
- Deployment OS: GitHub Actions

It appears after a [discussion](https://github.com/deployphp/deployer/discussions/2508) that using the array notation for scripts.

```
  yarn:run:prod:
    script:
      - 'cd {{release_or_current_path}} && yarn run prod'
```

Does not run properly vs something like:

```
  yarn:run:prod:
    script: 'cd {{release_or_current_path}} && yarn run prod'
```

**Comment by lorisleiva** [comment]
Okay I found the issue. It's because of the regex here:

https://github.com/deployphp/deployer/blob/fb72c94804ceb850558ce7f1cd7a4d8c73dae5ae/src/Importer/Importer.php#L122-L126

I'll make a PR to make the regex a bit more flexible by recognising the existence of `&&`.

**Comment by iBotPeaches** [comment]
I gave this a shot on beta22 and still not working out :/

I see this output

```
done yarn:install 24s 997ms
task yarn:run:prod
done on prod
    
done yarn:run:prod 184ms
task deploy:symlink
[prod] run (man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) | grep -- --no-target-directory || true
[prod]   -T, --no-target-directory    treat DEST as a normal file
[prod] run mv -T /usr/share/nginx/html/release /usr/share/nginx/html/current
done on prod
```

I know `yarn run prod` takes more than 184ms. Running it on the server myself after it failed was:
```
                         
   Laravel Mix v6.0.16   
                         

✔ Compiled Successfully in 60211ms
```

Entire task list is:
```
tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - artisan:migrate
    - yarn:install
    - yarn:run:prod
    - deploy:publish
  yarn:run:prod:
    script:
      - 'cd {{release_or_current_path}} && yarn run prod'
```
