### ISSUE TITLE
Phar problems: crc32 mismatch on file

### ISSUE THREAD

**Issue by coffeeneer** [deployphp/deployer#2592]
I'm having some issues with deployer connections. When I try to `php ./vendor/bin/dep ssh test` it fails 50% of the time. This is both on my local machine running Arch as well on my Gitlab server in CI/CD. Php version is 8.0.7 on Arch, 8.0.5 on the alpine based docker image used for CI/CD in Gitlab.

- Deployer version: 7.0.0-beta.23
- Deployment OS: ubuntu (docker container) / archlinux

In testing I have reduced my deploy.yaml to a minimal setup like this:
``` yaml
config:
  application: APPNAME
  user: USER
  host: HOST
  base_deploy_path: "~/domains"
  repository: "REPONAME"

hosts:
  test:
    remote_user: "{{user}}"
    hostname: "{{host}}"
    deploy_path: "{{base_deploy_path}}/APPLICATION_URL"
```

This is what I get when the CD fails with this issue:
``` bash
$ php ./vendor/bin/dep deploy test
In ClassLoader.php line 444:
                                                                               
  include(phar:///builds/APPLICATION_NAME/vendor/deployer/dist/dep/vendor/com  
  poser/../../src/Selector/Selector.php): Failed to open stream: phar error:   
  internal corruption of phar "/builds/APPLICATION_NAME/vendor/deployer/dist/  
  dep" (crc32 mismatch on file "src/Selector/Selector.php")                    
                                                                               
deploy [--tag TAG] [--revision REVISION] [--branch BRANCH] [-o|--option OPTION] [-l|--limit LIMIT] [--no-hooks] [--plan] [--start-from START-FROM] [--log LOG] [--profile PROFILE] [--] [<selector>...]
```

The application server is running OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017. I could try to have that updated to a newer build as it seems a bit old to me.
