### ISSUE TITLE
git_clone_dissociate doesn't work in Deployer v7

### ISSUE THREAD

**Issue by sbrow** [deployphp/deployer#2598]
- Deployer version: Deployer 7.0.0-beta.23
- Deployment OS: Homestead v12.3.0 | Settler v11.3.0 | Ubuntu 20.04

I may be an idiot, but certain config options aren't working for me.

deploy.yaml
```yaml
import:
    - recipe/laravel.php

config:
  application: 'example'
  repository: 'https://github.com/laravel/laravel'

  # If yes, removes git information after cloning.
  # broken?
  git_clone_dissociate: no

  # Skip deployment if no changes have been pushed.
  # broken?  
  check_remote_head: yes

hosts:
  localhost:
    deploy_path: '~/{{application}}'

#tasks:

after:
  deploy:failed: deploy:unlock

```
