### ISSUE TITLE
Host key verification failed on same host different staging

### ISSUE THREAD

**Issue by sluxzer** [deployphp/deployer#2615]
- Deployer version: v7.0.0-beta.24
- Deployment OS: Ubuntu 20.04.1 LTS
- Trigger: Github Action

My client want using same server for bot Staging & Production, with just separate folder, so i only differ the stage & deploy_path, everything else is same.

but the problem is, it's working on staging. but return **Host key verification failed** on production.

error 
```
Run php vendor/bin/dep deploy production --branch="master" -vvv
  php vendor/bin/dep deploy production --branch="master" -vvv
  shell: /usr/bin/bash -e {0}
  env:
    SSH_AUTH_SOCK: /tmp/ssh-auth.sock
    DOT_ENV: ***
  
  connecting production
[production] ssh -O check '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' echo 2>&1
[production] Control socket connect(/dev/shm/e516e67c3c852e2ea5e6b86700a150d753dc3c39): No such file or directory
[production] ssh multiplexing initialization
[production] ssh -N '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/%C' root@198.100.100.100

In Process.php line 267:
                                                                               
  [Symfony\Component\Process\Exception\ProcessFailedException]                 
  The command "ssh -N '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60'  
   '-o' 'ControlPath=/dev/shm/%C' root@128.100.100.100" failed.                 
                                                                               
  Exit Code: 255(Unknown error)                                                
                                                                               
  Working directory: /home/runner/work/xavier-app/xavier-app                                                            
                                                                               
  Output:                                                                      
  ================                                                             
                                                                               
                                                                               
  Error Output:                                                                
  ================                                                             
  Host key verification failed.                                                
                                                                               

Exception trace:
  at /home/runner/work/xavier-app/xavier-app/vendor/symfony/process/Process.php:267
 Symfony\Component\Process\Process->mustRun() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/src/Component/Ssh/Client.php:143
 Deployer\Component\Ssh\Client->initMultiplexing() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/src/Component/Ssh/Client.php:122
 Deployer\Component\Ssh\Client->connect() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/src/Executor/Master.php:141
 Deployer\Executor\Master->connect() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/src/Command/MainCommand.php:117
 Deployer\Command\MainCommand->execute() at /home/runner/work/xavier-app/xavier-app/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /home/runner/work/xavier-app/xavier-app/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /home/runner/work/xavier-app/xavier-app/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /home/runner/work/xavier-app/xavier-app/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/src/Deployer.php:304
 Deployer\Deployer::run() at /home/runner/work/xavier-app/xavier-app/vendor/deployer/deployer/bin/dep:105

deploy [--tag TAG] [--revision REVISION] [--branch BRANCH] [-o|--option OPTION] [-l|--limit LIMIT] [--no-hooks] [--plan] [--start-from START-FROM] [--log LOG] [--profile PROFILE] [--] [<selector>...]

Error: Process completed with exit code 1.
````

deploy.php
```
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/npm.php';

set('application', 'Wuling Assistance App');
set('repository', 'git@github.com:xxx.git');
//set('ssh_multiplexing', false);

task('deploy:secrets', function () {
    file_put_contents(__DIR__ . '/.env', getenv('DOT_ENV'));
    upload('.env', get('deploy_path') . '/shared');
});

host('production')
    ->set('stage','production')
    ->set('remote_user', 'root')
    ->set('hostname', '198.100.100.100') // xavier.github.xxx
    ->set('deploy_path', '/var/www/xavier-production');

host('staging')
    ->set('stage','staging')
    ->set('remote_user', 'root')
    ->set('hostname', '198.100.100.100') // staging-xavier.github.xxx
    ->set('deploy_path', '/var/www/xavier-staging');

after('deploy:failed', 'deploy:unlock');

desc('Start of Deploy the application');

task('deploy', [
    'deploy:prepare',
    'deploy:vendors',
    'artisan:storage:link',
    'artisan:view:cache',
    'artisan:config:cache',
    'artisan:migrate',
    'artisan:queue:restart',
    'npm:install',
    'npm:run:prod',
    'deploy:publish',
]);

desc('compile js to production');

task('npm:run:prod', function () {
    cd('{{release_path}}');
    run('npm run prod');
});

desc('End of Deploy the application');
```

.github/workflow
```
// Staging and it's working
- name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOST }}
      - name: Deploy to Production
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: php vendor/bin/dep deploy staging --branch="development" -vvv

// Production same config but failed
- name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOST }}
      - name: Deploy to Production
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: php vendor/bin/dep deploy production --branch="master" -vvv
```

Please Help. Thanks
