### ISSUE TITLE
Bitbucket - Permission denied (publickey)

### ISSUE THREAD

**Issue by sutcliffe121** [deployphp/deployer#2870]
- Deployer version: deployer:v7.0.0-rc.3
- Deployment OS: Windows 10 Pro 64-bit
- Laravel 8.33.1
- Composer v2.0.12 2021-04-01 10:14:59

My deployment is failing on task deploy update_code.

I run:
`php deployer.phar deploy -o ssh_multiplexing=false`

The output fails at:
```
task deploy:update_code
[prod]  error  in update_code.php on line 53:
[prod] run [ -f /var/www/myrepo/.dep/repo/HEAD ] || /usr/bin/git clone --mirror git@bitbucket.org:username/myrepo.git /var/www/myrepo/.dep/repo 2>&1
[prod] Cloning into bare repository '/var/www/myrepo/.dep/repo'...
[prod] git@bitbucket.org: Permission denied (publickey).
[prod] fatal: Could not read from remote repository.
[prod] Please make sure you have the correct access rights
[prod] and the repository exists.
[prod] exit code 128 (Invalid exit argument)
task deploy:failed
task deploy:unlock
```

My deploy.yaml is:
```
import: 
  - recipe/laravel.php
  - contrib/php-fpm.php

config:
  application: 'myrepo'
  repository: 'git@bitbucket.org:username/myrepo.git'
  php_fpm_version: '8.0'

hosts:
  prod:
    remote_user: root
    hostname: 'myip'
    deploy_path: '/var/www/myrepo'

tasks:
  deploy:
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:cache
    - deploy:publish
    - php-fpm:reload  
  build:
    - cd: '{{release_path}}'
    - run: 'npm run build'  

after:
  deploy:failed: deploy:unlock
```

I have tried:

1. Adding my id_rsa public key to Bitbucket via Personal settings and as an Access key on the repository as suggested here: https://github.com/deployphp/deployer/discussions/2865

2. Ensured my id_rsa key is passwordless (picked up from here: https://github.com/deployphp/deployer/issues/2861)

3. Verified my connection to Bitbucket using ssh -T git@bitbucket.org which returns - authenticated via ssh key. You can use git to connect to Bitbucket. Shell access is disabled

Any other help/suggestions, please?
