### ISSUE TITLE
The rsync array options should be merged with defaults

### ISSUE THREAD

**Issue by alexander-schranz** [deployphp/deployer#2890]
- Deployer version: 7.0.0-rc3
- Deployment OS: Mac OSX Monterey

      Please, provide a minimal reproducible example of deploy.php

https://deployer.org/docs/7.x/contrib/rsync

When defining `rsync` options only with `exclude`:

```php
set('rsync',[
    'exclude' => [
        '.git',
        'deploy.php',
        'assets',
    ],
]);
```

The deploy will fail:

```
[49.12.78.161]  ErrorException  in rsync.php on line 257:
[49.12.78.161]
[49.12.78.161]   Undefined array key "flags"
[49.12.78.161]
```

Not sure if it would be possible to define defaults somewhere else so I need not configure all rsync options.

PS: I hope its fine that I created seperate issues and not did pack all into one big issue.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2890">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2890/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2890/pledge.svg">
</picture>
</a>

**Comment by coreyworrell** [comment]
Can't you do:

```php
set('rsync', function () {
  return array_merge(get('rsync'), [
    'exclude' => [
      '.git',
      'deploy.php',
    ],
  ]);
});
```

**Comment by nvision-luxembourg** [comment]
Hello,
Same issue when importing in the deploy.php a yml file with custom conf
Placing it in the dpeloy.php makes no sens as the list of excluded files can changed from projects to another.

```
    rsync:
      exclude:
        - '.git*'
        - .bundler
        - deploy.php
```

We are obliged to put the whole thing
```
    rsync:
      exclude:
        - '.git*'
        - .bundler
        - deploy.php
           flags: 'rzcE'
      options: ['delete', 'delete-after', 'force']
      timeout: 3600
      include: []
      filter: []
      exclude-file: false
      include-file: false
      filter-file: false
      filter-perdir: false
```
