### ISSUE TITLE
scapeshellarg() in env_stringify()

### ISSUE THREAD

**Issue by refsz** [deployphp/deployer#2945]
- Deployer version: 7.0.0.rc4
- Deployment OS: Debian

I am currently experiencing the following TypeError with the following configuration.
```
[production]  TypeError  in helpers.php on line 89:
[production]
[production]   escapeshellarg() expects parameter 1 to be string, int given
[production]
```

```yaml
config:
  remote_user: ***
  base_path: ***
  repository: ***
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  php_fpm_service: 'php-fpm'
  nginx_service: 'nginx'

hosts:
  production:
    hostname: ***
    deploy_path: '{{ base_path }}/{{ alias }}'
    branch: 'master'
    crontab: config/deployment/hosts/production/crontab.txt
    env:
      DB_NAME: ***
      DB_HOSTNAME: ***
      DB_PORT: 3306
      DB_USER: ***
```

In the function _env_stringify_, the call to _escapeshellarg_ expects a string value. In my current configuration I have defined the DB_PORT as an int value. It's no problem for me to write this as a string at this point but shouldn't the value in _env_stringify_ possibly be cast to a string? I can provide a pull request for this.

What happens if someone defines an array inside env?
