### ISSUE TITLE
Deployer\Host\Host::getPort(): Return value must be of type ?int, string returned

### ISSUE THREAD

**Issue by simonbuehler** [deployphp/deployer#2973]
- Deployer version: 7
- Deployment OS: linux

hi,
i have following yaml
```yaml
import:
  - deploy/import-env-recipe.php
  - recipe/laravel.php

hosts:
  stage:
    port: '{{DEPLOYER_PORT}}'

tasks:
  build:
    - cd: '{{release_path}}'
    - run: 'npm run build'

after:
  deploy:failed: deploy:unlock
```
and `deploy/import-env-recipe.php` has this content:
```php
<?php

namespace Deployer;

use Dotenv\Dotenv;
$dotenv = Dotenv::createImmutable(dirname(__DIR__, 1), '.env');
$dotenv->load();
$dotenv->required(['DEPLOYER_HOSTNAME', 'DEPLOYER_REMOTE_USER', 'DEPLOYER_PORT', 'DEPLOYER_DEPLOY_PATH', 'DEPLOYER_IDENTITY_FILE'])->notEmpty();
set('DEPLOYER_HOSTNAME', env('DEPLOYER_HOSTNAME'));
set('DEPLOYER_REMOTE_USER', env('DEPLOYER_REMOTE_USER'));
set('DEPLOYER_PORT', intval(env('DEPLOYER_PORT')));
set('DEPLOYER_DEPLOY_PATH', env('DEPLOYER_DEPLOY_PATH'));
set('DEPLOYER_IDENTITY_FILE',env('DEPLOYER_IDENTITY_FILE'));

```

trying to use `dep ssh` this results in:

```
 TypeError  in Host.php on line 130:
 Deployer\Host\Host::getPort(): Return value must be of type ?int, string returned
```

i tried to step through it but the int val seems to be stored ok in the `values` array in `Configuration.php` but when returing from `parse` the Exception gets thrown.
