### ISSUE TITLE
Call to undefined function Deployer\env()

### ISSUE THREAD

**Issue by klaasnicolaas** [deployphp/deployer#3084]
- Deployer version: v7.0.0-rc.8
- Deployment OS: Ubuntu

I've been running into this problem for a while now, I can no longer use `env()` in my deploy.php file. In my case, I'm using it to get env variables from Github Action (in this case to get certain Slack credentials) in the deployment script. What am I missing to solve this problem?

**Error message:**
```bash
Run php vendor/bin/deployer.phar deploy -v
 Error  in deploy.php on line [13](https://github.com/platformdroneracingnl/race-event-registration/runs/5841728614?check_suite_focus=true#step:7:15):

  Call to undefined function Deployer\env()

Error: Process completed with exit code 1.
```

**Github Actions flow**
```yaml
- name: Run Deployment
  env:
    APP_SLACK_WEBHOOK: ${{ secrets.APP_SLACK_WEBHOOK }}
    RELEASE_VERSION: ${{ github.event.release.tag_name }}
  run: php vendor/bin/deployer.phar deploy -v
```

**Deploy.php**
```php
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'contrib/slack.php';
require 'contrib/npm.php';

set('application', 'PDRNL - Racing events');
set('ssh_multiplexing', true); // Speed up deployment
set('repository', 'git@github.com:platformdroneracingnl/race-event-registration.git');

set('slack_webhook', env('APP_SLACK_WEBHOOK')); // This is R13
set('release', env('RELEASE_VERSION'));
set('slack_success_text', 'Version *{{release}}* has just been successfully deployed on the live server.');
set('slack_failure_text', 'The deployment failed, check the build logs to see what went wrong.');
```
