### ISSUE TITLE
rsync_src is not specify to working dir, while using yml recipe

### ISSUE THREAD

**Issue by nstwfdev** [deployphp/deployer#3139]
- Deployer version: 7.0.0-rc.8
- Deployment OS: Ubuntu 20.04

From [documentation](https://deployer.org/docs/7.x/contrib/rsync#sample-configurations):
```
set('rsync_src', __DIR__);
```

If I dont define rsync_src in deploy.yml i got the following output:
```
[localhost] run rsync -rz -e 'ssh '-p' '522' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/deployer@example.com:522'' --delete --exclude='.git' --exclude='deploy.yml' --exclude='.gitlab-ci.yml' 'phar:///usr/local/bin/dep/contrib/' 'deployer@example.com:/srv/example.com/releases/1/'
[localhost] The source and destination cannot both be remote.
[localhost] rsync error: syntax or usage error (code 1) at main.c(1420) [Receiver=3.2.3]
```

While i define it with `__DIR__` or ` "__DIR__"` got following output:
```
  rsync_src: __DIR__

[localhost] run rsync -rz -e 'ssh '-p' '522' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/deployer@example.com'' --delete --exclude='.git' --exclude='deploy.yml' --exclude='.gitlab-ci.yml' '__DIR__/' 'deployer@example.com:/srv/example.com/releases/1/'
[localhost] rsync: [sender] change_dir "/builds/deployer/test-deploy-project/__DIR__" failed: No such file or directory (2)
[localhost] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
```

```
  rsync_src: "__DIR__"

[localhost] run rsync -rz -e 'ssh '-p' '522' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/deployer@example.com'' --delete --exclude='.git' --exclude='deploy.yml' --exclude='.gitlab-ci.yml' '__DIR__/' 'deployer@example.com:/srv/example.com/releases/1/'
[localhost] rsync: [sender] change_dir "/builds/deployer/test-deploy-project/__DIR__" failed: No such file or directory (2)
[localhost] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
```

deploy.yml
```yml
import:
  - contrib/rsync.php

hosts:
  stage:
    hostname: "example.com"

config:
  rsync:
    exclude:
      - .git
      - deploy.yml
      - .gitlab-ci.yml
    exclude-file: false
    include: [ ]
    include-file: false
    filter: [ ]
    filter-file: false
    filter-perdir: false
    flags: rz
    options:
      - delete
    timeout: 30

tasks:
  deploy:
    - rsync
```

My fix is:
```
  rsync_src: './'
or
  rsync_src: '.'
```
With that output all working fine:
```
run rsync -rz -e 'ssh '-p' '522' '-A' '-o' 'ControlMaster=auto' '-o' 'ControlPersist=60' '-o' 'ControlPath=/dev/shm/deployer@example.com'' --delete --exclude='.git' --exclude='deploy.yml' --exclude='.gitlab-ci.yml' './/' 'deployer@example.com:/srv/example.com/releases/20/'
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3139">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3139/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3139/pledge.svg">
</picture>
</a>
