### ISSUE TITLE
Allow replacing tasks with a group task and vice-versa in YAML

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3432]
In YAML when trying to replace a task with a group task is denied with the message:
> Tried to replace Task 'deploy:update_code' with a GroupTask or vice-versa. This is not supported. If you are sure you want to do that, remove the old task `Deployer::get()->tasks->remove(<taskname>)` and then re-add the task.

It would be useful if replacing is directly possible in YAML to make it easier readable.

Example:

```yaml
import:
  - recipe/composer.php

tasks:
  deploy:update_code:
   - deploy:update_code_live
   - deploy:update_code_staging
  deploy:update_code_live:
    - cd: '{{release_path}}'
    - run: 'echo Live'
    - select: 'alias=www.example.com'
  deploy:update_code_staging:
    - cd: '{{release_path}}'
    - run: 'echo Staging'
    - select: 'alias=staging.example.com'
```

Workaround:

```yaml
import:
  - recipe/composer.php

tasks:
  deploy:update_code:
    - run:': Skip this'
  deploy:update_code_grouptask:
   - deploy:update_code_live
   - deploy:update_code_staging
  deploy:update_code_live:
    - cd: '{{release_path}}'
    - run: 'echo Live'
    - select: 'alias=www.example.com'
  deploy:update_code_staging:
    - cd: '{{release_path}}'
    - run: 'echo Staging'
    - select: 'alias=staging.example.com'

after:
  deploy:update_code: deploy:update_code_grouptask:

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3432">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3432/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3432/pledge.svg">
</picture>
</a>
