### ISSUE TITLE
Fail at errors in multiline-commands

### ISSUE THREAD

**Issue by alexgit2k** [deployphp/deployer#3443]
If there is an error in a multiline command, deployer will not fail like bash-scripts do not fail unless the option "set -e -o pipefail" is used:

Example:
```yaml
hosts:
  test:
    local: true

tasks:
  singleFail:
    - run: 'echo "Start"'
    - run: 'false'
    - run: 'echo "End"'
  multiNoFail:
    - run: |
        echo "Start"
        false
        echo "End 1"
  multiFail:
    - run: |
        set -e -o pipefail
        echo "Start"
        false
        echo "End 1"
```

`dep -v single` fails, because commands are executed one by one
`dep -v multiNoFail` does not fail, because errors in multiline scripts are ignored
`dep -v multiFail` fails, because with `set` it fails at any error

I would suggest to automatically add the `set` when there is a multiline command.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3443">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3443/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3443/pledge.svg">
</picture>
</a>
