### ISSUE TITLE
Deploying a specific branch does not work from 7.2.0

### ISSUE THREAD

**Issue by alterphp** [deployphp/deployer#3519]
- Deployer version: 7.2.0
- Deployment OS: Ubuntu

Until 7.1.4, we could force the branch to deploy with `--branch` option if it was not configured on the targeted stage. From 7.2.0 it does not work.

Here is our `stages.yaml` config :
```
hosts:
    production:
        branch: master
        hostname: production-acme
        domain: www.tld.com
        remote_user: someuser
        deploy_path: /some/path
        keep_releases: 2
        forwardAgent: true

    .base-staging: &base-staging
        hostname: staging-acme
        domain: test.tld.com
        remote_user: someuser
        deploy_path: /some/path
        keep_releases: 2
        forwardAgent: true

    staging:
        <<: *base-staging
        branch: develop

    staging-spe:
        <<: *base-staging
        stage: staging-spe
```

We usually use target `staging` to deploy `develop` branch. But, in some cases, we want to deploy a specific branch to the staging target, so we use the following command : `vendor/bin/dep deploy staging-spe --branch my-specific-branch`.
 From 7.2.0 version, it deploys a revision from the develop branch :

```
task deploy:info
[test2-spe] info deploying fix/security-config
task deploy:setup
task deploy:lock
task deploy:release
task deploy:update_code
...
task deploy:store-revision
[test2-spe] REVISION: 3b2fafa1f391052fdb73eb96c35ef5b7584178f3
task deploy:cache:clear
task deploy:cache:warmup
task deploy:writable
...
```

Mentionned branch in the deploy:info is correct but the REVISION really deployed is wrong (it does not come from specified branch).
