### ISSUE TITLE
yaml upload does not allow array for src

### ISSUE THREAD

**Issue by pniederlag** [deployphp/deployer#3551]
- Deployer version: 7.3.0
- Deployment OS: ubuntu 20.04-lts

the upload function allows either string or array for src. Unfortunatly the schema.json (used to import from yaml to deployer) will fail for array, as it is expecting string only.

yaml that will fail:

```
tasks:
  deploy:upload:
    - upload:
        src: ["docker-compose.yml", "xyz.txt"]
        dest: '{{release_path}}/'
```
