### ISSUE TITLE
 Failed task with error message "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for _placeholder.test failed: Name or service not known" in Shopware recipe

### ISSUE THREAD

**Issue by gutschik** [deployphp/deployer#3581]
I'm using Deployer version 7.3.1 with the Shopware recipe to deploy my PHP application using the deployphp/action GitHub action. I have a task in my deploy.php file that is failing with the following error message:

```
"ERROR: Task sw-build-without-db:build failed!
[localhost] Warning: Failed to load apps. Loading apps from local. 
Message: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: 
getaddrinfo for _placeholder.test failed: Name or service not known"
```

This error message is preventing my deployment from succeeding.

**Environment:**

Deployer version: 7.3.1
PHP version: 8.1
Shopware recipe
Shopware Version: v6.4.20.1
GitHub action: deployphp/action
Operating system: Ubuntu 22.04.2

**Steps to reproduce:**

Use the provided `deploy.php` and `.github/workflows/deploy.yml` files.
Run the deployment with deployphp/action on a server where `_placeholder.test` cannot be resolved.

**Expected result:**

The deployment should complete successfully.

**Actual result:**

The `sw-build-without-db:build` task fails with the error message above.

**Additional context:**

I also tried different ubuntu versions and on self hosted runners, too. 

Please let me know if there is any additional information I can provide to help diagnose this issue. Thank you for your help!

deploy.php
```
<?php
namespace Deployer;
require 'recipe/shopware.php';
set('repository', '-v git@github.com/foo/bar-shopware6.git');

// Hosts
host('staging.foobar.com')
  ->set('bin/php', function () {
    return which('php');
  })
  ->set('remote_user', 'ssh1_dev_foobar')
  ->set('deploy_path', '/web/staging');

```

.github/workflows/deploy.yml
```
name: PHP Composer

on:
  push:
    branches: ['main']

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:2.2
          extensions: intl, mbstring, pdo_mysql, zip

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: deployphp/action
        uses: deployphp/action@v1
        with:
          dep: deploy
          # Private key for connecting to remote hosts. To generate private key:
          # `ssh-keygen -o -t rsa -C 'action@deployer.org'`.
          # Optional
          private-key: ${{ secrets.PRIVATE_KEY }}
          ssh-config: |
            Host *
              StrictHostKeyChecking no

```
