### ISSUE TITLE
YAML: allow to give description to groups tasks

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3656]
I have this task (group) defined via YAML:

```yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:publish

after:
  deploy:prepare:
    - typo3:create_default_folders
    - typo3:update:databaseschema
    - typo3:flush:caches
    - typo3:setup:extensions
    - typo3:flush:caches

  deploy:failed:
    - deploy:unlock
```

I'm trying to find a way to set the description of this task group so that `deployer dep list` shows a nice description and not only the key of the task.

Is there any way to do this?

_Originally posted by @oliverklee in https://github.com/deployphp/deployer/discussions/3504_

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3656">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3656/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3656/pledge.svg">
</picture>
</a>

**Comment by adpeyre** [comment]
Maybe you can try something like that :

```` yaml
tasks:
  deploy:
    - deploy:prepare
    - deploy:publish

after:
  deploy:prepare:
    desc: 'description'
    script:
       - typo3:create_default_folders
      - typo3:update:databaseschema
      - typo3:flush:caches
      - typo3:setup:extensions
      - typo3:flush:caches

  deploy:failed:
    - deploy:unlock
````
