### ISSUE TITLE
YAML configuration requires specific order of entries

### ISSUE THREAD

**Issue by boesing** [deployphp/deployer#3704]
- Deployer version: 9.1.0
- Deployment OS: Debian 12

It seems that deployer reads configuration as it comes in.
I personally would expect the order to be:

1. `config`
2. `import`
3. `tasks`
4. `after`/`before`

The main reason for this is that:
- one might provide required config variables for recipes before actually importing the recipe.
- `tasks` might want to `invoke` tasks from `import`ed recipes
- `after`/ `before` wants to queue `tasks` `after` or `before` tasks from `import`ed recipes

----

Problematic YAML order:

```yaml
tasks:
  "deploy:prepare:whatever":
    - info: "Whatever"
after:
  "deploy:prepare": "deploy:prepare:whatever"
import:
  - 'recipe/common.php'
```

Working YAML order:

```yaml
import:
  - 'recipe/common.php'
tasks:
  "deploy:prepare:whatever":
    - info: "Whatever"
after:
  "deploy:prepare": "deploy:prepare:whatever"
```
