### ISSUE TITLE
Breaking new patch for TYPO3 recipe usage

### ISSUE THREAD

**Issue by rlvk-tc** [deployphp/deployer#3722]
- Deployer version: 7.3.2
- Deployment OS: Windows and Mac

```yaml
import:
  - recipe/typo3.php

config:
  repository: '[git-ssh-repository]'
  typo3_webroot: 'public'
  keep_releases: 5
  shared_dirs:
    - '{{typo3_webroot}}/fileadmin'
    - '{{typo3_webroot}}/typo3temp'
    - 'config'
  shared_files:
    - '{{typo3_webroot}}/.htaccess'
    - '{{typo3_webroot}}/apple-touch-icon.png'
    - '{{typo3_webroot}}/favicon.ico'

hosts:
  [server-ip]:
    remote_user: deployer
    deploy_path: '[server-deploy-path]'

tasks:
  typo3:cache:flush:
    - cd: "{{release_path}}"
    - run: "{{bin/composer}} exec typo3 cache:flush"
  deploy:
  - 'deploy:prepare'
  - 'deploy:vendors'
  - 'deploy:symlink'
  - 'typo3:cache:flush'
  - 'deploy:unlock'
  - 'deploy:cleanup'
  - 'deploy:success'

after:
  deploy:failed: deploy:unlock
```

After updating from Deployer 7.3.1 -> 7.3.2, my deployments are no longer working. After investigating a little bit, I can see that the TYPO3 recipe that I'm depending on, has been changed quite a lot, and is now using some different steps in the deploy task. Specifically it is the rsync that is causing issues, as it seems that it doesn't work with the git repository setup, that I'm running. It tells me that the local path cannot be remote.

Anyone had similar issues and can help me, so I can stay up-to-date?
