### ISSUE TITLE
There are no invoke() in YAML tasks

### ISSUE THREAD

**Issue by ronald2wing** [deployphp/deployer#3734]
- Deployer version: v7.3.3
- Deployment OS: Ubuntu

```
tasks:
  provision:custom_deployer:
    - run: "apt install acl"
    - run: "apt install whois"
    - run: "groupadd --system caddy"
    - invoke: provision:deployer

```

I don't see https://deployer.org/docs/7.x/api#invoke in https://github.com/deployphp/deployer/blob/master/src/schema.json

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3734">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3734/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3734/pledge.svg">
</picture>
</a>
