### ISSUE TITLE
Provision: file_get_contents(./Caddyfile): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mariomka** [deployphp/deployer#3819]
- Deployer version:  7.4.0
- Deployment OS: Ubuntu 20.04

I'm trying to provision a clean server in Hetzner Cloud (CCX13 - dedicated 2 vCPU 8GB RAM) with the Laravel recipe. I got an error; I tried several times with different PHP versions and removed and created the server. 

The error is the following:

```
[servername]  ErrorException  in website.php on line 24:
[servername]
[servername]   file_get_contents(./Caddyfile): Failed to open stream: No such file or directory
[servername]
ERROR: Task provision:website failed!
```

The `deploy.yaml` file:

```yaml
import:
  - recipe/laravel.php

config:
  repository: 'git@github.com:XXX/xxx'

hosts:
  servername:
    remote_user: deployer
    deploy_path: '/var/www/my-project'

tasks:
  build:
    - run: uptime

after:
  deploy:failed: deploy:unlock
```
