### ISSUE TITLE
Bump php/symfony dependencies or make it less strict

### ISSUE THREAD

**Issue by ITspirit** [deployphp/deployer#3867]
Bump Dependencies or make it less strict. Otherwise these tool will be blocked out for further usage.

Currently lot of dependencies are really selective, without need.

```yaml
    "require": {
        "php": "^8.0|^7.3",
        "symfony/console": "^5.4.9",
        "symfony/process": "^5",
        "symfony/yaml": "^5"
    },
```

Why not make it less strict?

```yaml
    "require": {
        "php": ">=7.3",
        "symfony/console": ">=5.4.9",
        "symfony/process": ">=5",
        "symfony/yaml": ">=5"
    },
```
So i could use it in projects with much modern dependencies.

Any concerns about this?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3867">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3867/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3867/pledge.svg">
</picture>
</a>
