### ISSUE TITLE
Please add checksum deployer.phar archive

### ISSUE THREAD

**Issue by tebaly** [deployphp/deployer#816]
| Q | A |
| --- | --- |
| Issue Type | Feature Request |
| Deployer Version | N/A |
| Local Machine OS | N/A |
| Remote Machine OS | N/A |
### Description

Pages:
http://deployer.org/docs/getting-started
http://deployer.org/docs/installation

Please add checksum deployer.phar archive MD5 and sha256 to use with _ansible_ like

```
- name: download file with check (md5)
  get_url:  
    url: http://deployer.org/deployer.phar
    dest: /usr/local/bin/dep
    checksum: md5:66dffb5228a211e61d6d7ef4a86f5758
```
