### ISSUE TITLE
Hidden Keys in YAML config

### ISSUE THREAD

**Issue by ikappas** [deployphp/deployer#859]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
Keys that start with a dot (.) will be not processed by Deployer. You can use this feature to ignore servers, or use the special YAML features and transform the hidden keys into templates.

In the following example, `.key_name` will be ignored:
```yaml
.key_name:
  branch: master
  options:
    - some option
```
Hidden keys can be hashes, but you are also allowed to use different types of structures to leverage special YAML features.

#### Before
```yaml
staging:
  application: example
  repository: git@github.com:company/example.git
  deploy_path: '/var/www/{{application}}'
  user: deploy
  identity_file: ~
  forward_agent: true
  branch: develop
  stage: staging
  host: stage.example.com

production:
  application: example
  repository: git@github.com:company/example.git
  deploy_path: '/var/www/{{application}}'
  user: deploy
  identity_file: ~
  forward_agent: true
  branch: master
  stage: production
  host: www.example.com
```
#### After
```yaml
.common: &common
  application: example
  repository: git@github.com:company/example.git
  deploy_path: '/var/www/{{application}}'
  user: deploy
  identity_file: ~
  forward_agent: true

staging:
  <<: *common
  branch: develop
  stage: staging
  host: stage.example.com

production:
  <<: *common
  branch: master
  stage: production
  host: www.example.com
```
### Implementation/Patch
in src/Bootstrap/BootstrapByConfigFile.php:118
#### Change:
```php
        foreach ($this->configFileContent as $key => $cnf) {
            if (isset($cnf['cluster']) && $cnf['cluster']) {
                $this->clusterConfig[$key] = $cnf;
            } else {
                $this->serverConfig[$key] = $cnf;
            }
        }
```
#### To:
```php
        foreach ($this->configFileContent as $key => $cnf) {
            // Ignore hidden configuration keys
            if (substr($key, 0, 1 ) === '.') {
                continue;
            }
            if (isset($cnf['cluster']) && $cnf['cluster']) {
                $this->clusterConfig[$key] = $cnf;
            } else {
                $this->serverConfig[$key] = $cnf;
            }
        }
```
### References
- https://github.com/ikappas/deployer/blob/feature/yaml-hidden-keys/src/Bootstrap/BootstrapByConfigFile.php
- https://learnxinyminutes.com/docs/yaml/
