### ISSUE TITLE
Using ~ in the destination of upload() results in files not being uploaded

### ISSUE THREAD

**Issue by mrchimp** [deployphp/deployer#907]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.1
| Local Machine OS  | OS X Sierra
| Remote Machine OS | Ubuntu 14.04

### Description 
When using `~` in the destination of the `upload()` function, no files are uploaded. No errors are given - it appears to succeed but the files aren't created on the server. Using `-vvv` shows that is attempting to upload the correct files.

### Content of `deploy.php`
```php
<?php

namespace Deployer;

require 'recipe/common.php';

set('repository', 'git@bitbucket.org:............');
set('theme_dir', 'mytheme');
set('writable_use_sudo', false);
set('writable_mode', 'chmod');

serverList('servers.yml');
set('local_theme', __DIR__ . '/web/app/themes/{{theme_dir}}');
set('shared_dirs', ['web/app/uploads']);
set('shared_files', ['.env', 'web/.htaccess']);

task('deploy:upload_dist', function() {
  upload('{{local_theme}}/dist', '{{release_path}}/web/app/themes/{{theme_dir}}/dist/');
})->desc('Upload dist folder to server');

task('deploy:theme_composer', function() {
  cd('{{release_path}}/web/app/themes/{{theme_dir}}');
  run('composer install');
})->desc('Remote composer install');

task('setup', [
  'deploy:prepare',
])->desc('Initial deployment setup');

task('deploy', [
  'deploy:release',
  'deploy:update_code',
  'deploy:vendors',
  'deploy:theme_composer',
  'deploy:shared',
  'deploy:upload_dist',
  'deploy:symlink',
  'cleanup'
])->desc('Executing Deploy task');
```

### Content of servers.yml

```yaml
stage:
  host: example.com
  user: admin
  identity_file: ~
  stage: staging
  deploy_path: ~/web/example.com/deployer
  # deploy_path: /home/admin/web/example.com/deployer # This works
  branch: dev
```

### Output log
I'm not at my work machine so don't have the output but I don't think it would help with debugging. The output is that same as when it does work - all green.
