### ISSUE TITLE
Cannot use get function in task with once method

### ISSUE THREAD

**Issue by ozgurky** [deployphp/deployer#921]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | Ubuntu 16.04 LTS
| Remote Machine OS | Ubuntu 16.04 LTS

 I use a custom task for running artisan migrate on a lumen project and I want this task to run once. 

```
task('deploy:artisan_migrate', function () {
    run("cd {{release_path}} && php artisan migrate --force");
})->once();
```
It returns `Configuration parameter deploy_path does not exists.` error but this parameter is defined in yml file. I've also tried get('release_path') and got same error. When i remove once method it seems ok.

Is not possible to use **get** function in a task with once method?

**Comment by elfet** [comment]
What do you think `get('release_path')` should return in `once()` task?

**Comment by ozgurky** [comment]
Thanks for reply, I've multiple servers for production but they don't have any git installation. So i decided to run git on local server, compress codes with tar and upload tar file to these servers. I want to run git clone command only once for fast deployment. Here is my code:

```
task('local:update_code', function () {
    $repository = trim(get('repository'));
    $branch = get('branch');
    $git = get('bin/git');
    $gitCache = get('git_cache');
    $depth = $gitCache ? '' : '--depth 1';

    if (input()->hasOption('tag')) {
        $tag = input()->getOption('tag');
    } elseif (input()->hasOption('revision')) {
        $revision = input()->getOption('revision');
    }

    $at = '';
    if (!empty($tag)) {
        $at = "-b $tag";
    } elseif (!empty($branch)) {
        $at = "-b $branch";
    }

    if (!empty($revision)) {
        runLocally("$git clone $at --recursive -q $repository {{local_path}} 2>&1");
        runLocally("cd {{local_path}} && $git checkout $revision");
    } else {
        runLocally("$git clone $at $depth --recursive -q $repository {{local_path}} 2>&1");
    }
})->once()->desc('Updating local code');
```

branch parameter is defined in server.yml file but when i use task with once get('branch') returns empty.

Is there a way for using yml file parameters with once method?

**Comment by elfet** [comment]
```yml
prod:
    ...
    branch: prod

beta:
    branch: beta
```


What should `gert('branch')` return?

**Comment by ozgurky** [comment]
```
prod-b:
  ...
  stage: develop
  branch: develop

prod-c:
  stage: production
  branch: master
```
When I run deployer like `dep  -f=deploy.php deploy develop` it should return develop and when the command is

`dep  -f=deploy.php deploy production` it should return master or do i completely misunderstand.

**Comment by elfet** [comment]
And for this? `dep deploy develop`

```
prod-a:
  ...
  stage: develop
  branch: feature

prod-b:
  ...
  stage: develop
  branch: develop

prod-c:
  stage: production
  branch: master
```
